<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PackageJsonName Condition="$(PackageJsonName) == ''">indice.dex.app</PackageJsonName>
    <PackageJsonVersion Condition="$(PackageJsonVersion) == ''">0.0.0</PackageJsonVersion>
    <PackageJsonScriptsNg Condition="$(PackageJsonScriptsNg) == ''">ng</PackageJsonScriptsNg>
    <PackageJsonScriptsStart Condition="$(PackageJsonScriptsStart) == ''">ng serve</PackageJsonScriptsStart>
    <PackageJsonScriptsBuild Condition="$(PackageJsonScriptsBuild) == ''">ng build</PackageJsonScriptsBuild>
    <PackageJsonScriptsBuildTemplate Condition="$(PackageJsonScriptsBuildTemplate) == ''">ng build --configuration template</PackageJsonScriptsBuildTemplate>
    <PackageJsonScriptsWatch Condition="$(PackageJsonScriptsWatch) == ''">ng build --watch --configuration development</PackageJsonScriptsWatch>
    <PackageJsonScriptsTest Condition="$(PackageJsonScriptsTest) == ''">ng test</PackageJsonScriptsTest>
    <PackageJsonScriptsGenerateApi Condition="$(PackageJsonScriptsGenerateApi) == ''">cd src/app/core/services &amp;&amp; nswag run dex-api.nswag</PackageJsonScriptsGenerateApi>
    <PackageJsonPrettierPrintwidth Condition="$(PackageJsonPrettierPrintwidth) == ''">100</PackageJsonPrettierPrintwidth>
    <PackageJsonPrettierSinglequote Condition="$(PackageJsonPrettierSinglequote) == ''">true</PackageJsonPrettierSinglequote>
    <PackageJsonPrettierOverrides Condition="$(PackageJsonPrettierOverrides) == ''">[
  {
    "files": "*.html",
    "options": {
      "parser": "angular"
    }
  }
]</PackageJsonPrettierOverrides>
    <PackageJsonPrivate Condition="$(PackageJsonPrivate) == ''">true</PackageJsonPrivate>
    <PackageJsonDependenciesAngularCommon Condition="$(PackageJsonDependenciesAngularCommon) == ''">^20.3.0</PackageJsonDependenciesAngularCommon>
    <PackageJsonDependenciesAngularCompiler Condition="$(PackageJsonDependenciesAngularCompiler) == ''">^20.3.0</PackageJsonDependenciesAngularCompiler>
    <PackageJsonDependenciesAngularCore Condition="$(PackageJsonDependenciesAngularCore) == ''">^20.3.0</PackageJsonDependenciesAngularCore>
    <PackageJsonDependenciesAngularForms Condition="$(PackageJsonDependenciesAngularForms) == ''">^20.3.0</PackageJsonDependenciesAngularForms>
    <PackageJsonDependenciesAngularPlatformBrowser Condition="$(PackageJsonDependenciesAngularPlatformBrowser) == ''">^20.3.0</PackageJsonDependenciesAngularPlatformBrowser>
    <PackageJsonDependenciesAngularRouter Condition="$(PackageJsonDependenciesAngularRouter) == ''">^20.3.0</PackageJsonDependenciesAngularRouter>
    <PackageJsonDependenciesIndiceNgAuth Condition="$(PackageJsonDependenciesIndiceNgAuth) == ''">0.5.2</PackageJsonDependenciesIndiceNgAuth>
    <PackageJsonDependenciesNgxMarkdown Condition="$(PackageJsonDependenciesNgxMarkdown) == ''">^20.0.0</PackageJsonDependenciesNgxMarkdown>
    <PackageJsonDependenciesMarked Condition="$(PackageJsonDependenciesMarked) == ''">^15.0.0</PackageJsonDependenciesMarked>
    <PackageJsonDependenciesOidcClientTs Condition="$(PackageJsonDependenciesOidcClientTs) == ''">^3.5.0</PackageJsonDependenciesOidcClientTs>
    <PackageJsonDependenciesRxjs Condition="$(PackageJsonDependenciesRxjs) == ''">~7.8.0</PackageJsonDependenciesRxjs>
    <PackageJsonDependenciesTslib Condition="$(PackageJsonDependenciesTslib) == ''">^2.3.0</PackageJsonDependenciesTslib>
    <PackageJsonDevdependenciesAngularBuild Condition="$(PackageJsonDevdependenciesAngularBuild) == ''">^20.3.6</PackageJsonDevdependenciesAngularBuild>
    <PackageJsonDevdependenciesAngularCli Condition="$(PackageJsonDevdependenciesAngularCli) == ''">^20.3.6</PackageJsonDevdependenciesAngularCli>
    <PackageJsonDevdependenciesAngularCompilerCli Condition="$(PackageJsonDevdependenciesAngularCompilerCli) == ''">^20.3.0</PackageJsonDevdependenciesAngularCompilerCli>
    <PackageJsonDevdependenciesTailwindcssPostcss Condition="$(PackageJsonDevdependenciesTailwindcssPostcss) == ''">^4.3.1</PackageJsonDevdependenciesTailwindcssPostcss>
    <PackageJsonDevdependenciesTypesJasmine Condition="$(PackageJsonDevdependenciesTypesJasmine) == ''">~5.1.0</PackageJsonDevdependenciesTypesJasmine>
    <PackageJsonDevdependenciesDaisyui Condition="$(PackageJsonDevdependenciesDaisyui) == ''">^5.5.23</PackageJsonDevdependenciesDaisyui>
    <PackageJsonDevdependenciesJasmineCore Condition="$(PackageJsonDevdependenciesJasmineCore) == ''">~5.9.0</PackageJsonDevdependenciesJasmineCore>
    <PackageJsonDevdependenciesKarma Condition="$(PackageJsonDevdependenciesKarma) == ''">~6.4.0</PackageJsonDevdependenciesKarma>
    <PackageJsonDevdependenciesKarmaChromeLauncher Condition="$(PackageJsonDevdependenciesKarmaChromeLauncher) == ''">~3.2.0</PackageJsonDevdependenciesKarmaChromeLauncher>
    <PackageJsonDevdependenciesKarmaCoverage Condition="$(PackageJsonDevdependenciesKarmaCoverage) == ''">~2.2.0</PackageJsonDevdependenciesKarmaCoverage>
    <PackageJsonDevdependenciesKarmaJasmine Condition="$(PackageJsonDevdependenciesKarmaJasmine) == ''">~5.1.0</PackageJsonDevdependenciesKarmaJasmine>
    <PackageJsonDevdependenciesKarmaJasmineHtmlReporter Condition="$(PackageJsonDevdependenciesKarmaJasmineHtmlReporter) == ''">~2.1.0</PackageJsonDevdependenciesKarmaJasmineHtmlReporter>
    <PackageJsonDevdependenciesNswag Condition="$(PackageJsonDevdependenciesNswag) == ''">^14.7.1</PackageJsonDevdependenciesNswag>
    <PackageJsonDevdependenciesPostcss Condition="$(PackageJsonDevdependenciesPostcss) == ''">^8.5.15</PackageJsonDevdependenciesPostcss>
    <PackageJsonDevdependenciesTailwindcss Condition="$(PackageJsonDevdependenciesTailwindcss) == ''">^4.3.1</PackageJsonDevdependenciesTailwindcss>
    <PackageJsonDevdependenciesTypescript Condition="$(PackageJsonDevdependenciesTypescript) == ''">~5.9.2</PackageJsonDevdependenciesTypescript>
  </PropertyGroup>
</Project>