//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indice.Features.Identity.UI.Telemetry {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TelemetryJavascriptResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelemetryJavascriptResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indice.Features.Identity.UI.Telemetry.TelemetryJavascriptResources", typeof(TelemetryJavascriptResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appInsights.setAuthenticatedUserContext(&quot;{0}&quot;);.
        /// </summary>
        internal static string JavaScriptAuthSnippet {
            get {
                return ResourceManager.GetString("JavaScriptAuthSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function(T,l,y){var S=T.location,k=&quot;script&quot;,D=&quot;instrumentationKey&quot;,C=&quot;ingestionendpoint&quot;,I=&quot;disableExceptionTracking&quot;,E=&quot;ai.device.&quot;,b=&quot;toLowerCase&quot;,w=&quot;crossOrigin&quot;,N=&quot;POST&quot;,e=&quot;appInsightsSDK&quot;,t=y.name||&quot;appInsights&quot;;(y.name||T[e])&amp;&amp;(T[e]=t);var n=T[t]||function(d){var g=!1,f=!1,m={initialize:!0,queue:[],sv:&quot;5&quot;,version:2,config:d};function v(e,t){var n={},a=&quot;Browser&quot;;return n[E+&quot;id&quot;]=a[b](),n[E+&quot;type&quot;]=a,n[&quot;ai.operation.name&quot;]=S&amp;&amp;S.pathname||&quot;_unknown_&quot;,n[&quot;ai.internal.sdkVersion&quot;]=&quot;javascript:snippet_&quot;+(m. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JavaScriptSnippet {
            get {
                return ResourceManager.GetString("JavaScriptSnippet", resourceCulture);
            }
        }
    }
}
