<Project>
  <ItemGroup Condition=" '$(OutputType)' == 'Exe' ">
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup Condition=" '$(OutputType)' == 'Exe' ">
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.0" />
  </ItemGroup>
</Project>