<Project>
    <PropertyGroup Label="Assembly Common">
      <Copyright>Copyright (c) Indice</Copyright>
      <LangVersion>Latest</LangVersion>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
      <!--<TargetFramework></TargetFramework>-->
      <OutputType>Exe</OutputType>
      <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>
    <PropertyGroup Label="Package Common">
      <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>