#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indice.Features.GovGr.Proxies.Gsis
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicInputRtBase", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Indice.Features.GovGr.Proxies.Gsis.RgWsPublicInputRtUser))]
    public partial class RgWsPublicInputRtBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicInputRtUser", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    public partial class RgWsPublicInputRtUser : Indice.Features.GovGr.Proxies.Gsis.RgWsPublicInputRtBase
    {
        
        private string afmCalledByField;
        
        private string afmCalledForField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string afmCalledBy
        {
            get
            {
                return this.afmCalledByField;
            }
            set
            {
                this.afmCalledByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string afmCalledFor
        {
            get
            {
                return this.afmCalledForField;
            }
            set
            {
                this.afmCalledForField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicBasicRtBase", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Indice.Features.GovGr.Proxies.Gsis.RgWsPublicBasicRtUser))]
    public partial class RgWsPublicBasicRtBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicBasicRtUser", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    public partial class RgWsPublicBasicRtUser : Indice.Features.GovGr.Proxies.Gsis.RgWsPublicBasicRtBase
    {
        
        private string afmField;
        
        private System.Nullable<System.DateTime> stopDateField;
        
        private string postalAddressNoField;
        
        private string doyDescrField;
        
        private string doyField;
        
        private string onomasiaField;
        
        private string legalStatusDescrField;
        
        private System.Nullable<System.DateTime> registDateField;
        
        private string deactivationFlagField;
        
        private string deactivationFlagDescrField;
        
        private string postalAddressField;
        
        private string firmFlagDescrField;
        
        private string commerTitleField;
        
        private string postalAreaDescriptionField;
        
        private string INiFlagDescrField;
        
        private string postalZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string afm
        {
            get
            {
                return this.afmField;
            }
            set
            {
                this.afmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> stopDate
        {
            get
            {
                return this.stopDateField;
            }
            set
            {
                this.stopDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string postalAddressNo
        {
            get
            {
                return this.postalAddressNoField;
            }
            set
            {
                this.postalAddressNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string doyDescr
        {
            get
            {
                return this.doyDescrField;
            }
            set
            {
                this.doyDescrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string doy
        {
            get
            {
                return this.doyField;
            }
            set
            {
                this.doyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string onomasia
        {
            get
            {
                return this.onomasiaField;
            }
            set
            {
                this.onomasiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string legalStatusDescr
        {
            get
            {
                return this.legalStatusDescrField;
            }
            set
            {
                this.legalStatusDescrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> registDate
        {
            get
            {
                return this.registDateField;
            }
            set
            {
                this.registDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string deactivationFlag
        {
            get
            {
                return this.deactivationFlagField;
            }
            set
            {
                this.deactivationFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string deactivationFlagDescr
        {
            get
            {
                return this.deactivationFlagDescrField;
            }
            set
            {
                this.deactivationFlagDescrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public string postalAddress
        {
            get
            {
                return this.postalAddressField;
            }
            set
            {
                this.postalAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public string firmFlagDescr
        {
            get
            {
                return this.firmFlagDescrField;
            }
            set
            {
                this.firmFlagDescrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string commerTitle
        {
            get
            {
                return this.commerTitleField;
            }
            set
            {
                this.commerTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public string postalAreaDescription
        {
            get
            {
                return this.postalAreaDescriptionField;
            }
            set
            {
                this.postalAreaDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public string INiFlagDescr
        {
            get
            {
                return this.INiFlagDescrField;
            }
            set
            {
                this.INiFlagDescrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public string postalZipCode
        {
            get
            {
                return this.postalZipCodeField;
            }
            set
            {
                this.postalZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RgWsPublicFirmActRtUserArray", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl", ItemName="RgWsPublicFirmActRtUser")]
    public class RgWsPublicFirmActRtUserArray : System.Collections.Generic.List<Indice.Features.GovGr.Proxies.Gsis.RgWsPublicFirmActRtUser>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicFirmActRtUser", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    public partial class RgWsPublicFirmActRtUser : Indice.Features.GovGr.Proxies.Gsis.RgWsPublicFirmActRtBase
    {
        
        private string firmActDescrField;
        
        private string firmActKindField;
        
        private string firmActKindDescrField;
        
        private System.Nullable<decimal> firmActCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firmActDescr
        {
            get
            {
                return this.firmActDescrField;
            }
            set
            {
                this.firmActDescrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firmActKind
        {
            get
            {
                return this.firmActKindField;
            }
            set
            {
                this.firmActKindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firmActKindDescr
        {
            get
            {
                return this.firmActKindDescrField;
            }
            set
            {
                this.firmActKindDescrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> firmActCode
        {
            get
            {
                return this.firmActCodeField;
            }
            set
            {
                this.firmActCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicFirmActRtBase", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Indice.Features.GovGr.Proxies.Gsis.RgWsPublicFirmActRtUser))]
    public partial class RgWsPublicFirmActRtBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenWsErrorRtBase", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Indice.Features.GovGr.Proxies.Gsis.GenWsErrorRtUser))]
    public partial class GenWsErrorRtBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenWsErrorRtUser", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    public partial class GenWsErrorRtUser : Indice.Features.GovGr.Proxies.Gsis.GenWsErrorRtBase
    {
        
        private string errorDescrField;
        
        private string errorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string errorDescr
        {
            get
            {
                return this.errorDescrField;
            }
            set
            {
                this.errorDescrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl", ConfigurationName="Indice.Features.GovGr.Proxies.Gsis.RgWsPublic")]
    public interface RgWsPublic
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gr/gsis/rgwspublic/RgWsPublic.wsdl/rgWsPublicAfmMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<Indice.Features.GovGr.Proxies.Gsis.rgWsPublicAfmMethodResponse> rgWsPublicAfmMethodAsync(Indice.Features.GovGr.Proxies.Gsis.rgWsPublicAfmMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gr/gsis/rgwspublic/RgWsPublic.wsdl/rgWsPublicVersionInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Indice.Features.GovGr.Proxies.Gsis.rgWsPublicVersionInfoResponse> rgWsPublicVersionInfoAsync(Indice.Features.GovGr.Proxies.Gsis.rgWsPublicVersionInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rgWsPublicAfmMethod", WrapperNamespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl", IsWrapped=true)]
    public partial class rgWsPublicAfmMethodRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Indice.Features.GovGr.Proxies.Gsis.RgWsPublicInputRtUser RgWsPublicInputRt_in;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public Indice.Features.GovGr.Proxies.Gsis.RgWsPublicBasicRtUser RgWsPublicBasicRt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public Indice.Features.GovGr.Proxies.Gsis.RgWsPublicFirmActRtUserArray arrayOfRgWsPublicFirmActRt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public decimal pCallSeqId_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public Indice.Features.GovGr.Proxies.Gsis.GenWsErrorRtUser pErrorRec_out;
        
        public rgWsPublicAfmMethodRequest()
        {
        }
        
        public rgWsPublicAfmMethodRequest(Indice.Features.GovGr.Proxies.Gsis.RgWsPublicInputRtUser RgWsPublicInputRt_in, Indice.Features.GovGr.Proxies.Gsis.RgWsPublicBasicRtUser RgWsPublicBasicRt_out, Indice.Features.GovGr.Proxies.Gsis.RgWsPublicFirmActRtUserArray arrayOfRgWsPublicFirmActRt_out, decimal pCallSeqId_out, Indice.Features.GovGr.Proxies.Gsis.GenWsErrorRtUser pErrorRec_out)
        {
            this.RgWsPublicInputRt_in = RgWsPublicInputRt_in;
            this.RgWsPublicBasicRt_out = RgWsPublicBasicRt_out;
            this.arrayOfRgWsPublicFirmActRt_out = arrayOfRgWsPublicFirmActRt_out;
            this.pCallSeqId_out = pCallSeqId_out;
            this.pErrorRec_out = pErrorRec_out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rgWsPublicAfmMethodResponse", WrapperNamespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl", IsWrapped=true)]
    public partial class rgWsPublicAfmMethodResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Indice.Features.GovGr.Proxies.Gsis.RgWsPublicBasicRtUser RgWsPublicBasicRt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public Indice.Features.GovGr.Proxies.Gsis.RgWsPublicFirmActRtUserArray arrayOfRgWsPublicFirmActRt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public decimal pCallSeqId_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public Indice.Features.GovGr.Proxies.Gsis.GenWsErrorRtUser pErrorRec_out;
        
        public rgWsPublicAfmMethodResponse()
        {
        }
        
        public rgWsPublicAfmMethodResponse(Indice.Features.GovGr.Proxies.Gsis.RgWsPublicBasicRtUser RgWsPublicBasicRt_out, Indice.Features.GovGr.Proxies.Gsis.RgWsPublicFirmActRtUserArray arrayOfRgWsPublicFirmActRt_out, decimal pCallSeqId_out, Indice.Features.GovGr.Proxies.Gsis.GenWsErrorRtUser pErrorRec_out)
        {
            this.RgWsPublicBasicRt_out = RgWsPublicBasicRt_out;
            this.arrayOfRgWsPublicFirmActRt_out = arrayOfRgWsPublicFirmActRt_out;
            this.pCallSeqId_out = pCallSeqId_out;
            this.pErrorRec_out = pErrorRec_out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rgWsPublicVersionInfo", WrapperNamespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl", IsWrapped=true)]
    public partial class rgWsPublicVersionInfoRequest
    {
        
        public rgWsPublicVersionInfoRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rgWsPublicVersionInfoResponse", WrapperNamespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl", IsWrapped=true)]
    public partial class rgWsPublicVersionInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public rgWsPublicVersionInfoResponse()
        {
        }
        
        public rgWsPublicVersionInfoResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface RgWsPublicChannel : Indice.Features.GovGr.Proxies.Gsis.RgWsPublic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class RgWsPublicClient : System.ServiceModel.ClientBase<Indice.Features.GovGr.Proxies.Gsis.RgWsPublic>, Indice.Features.GovGr.Proxies.Gsis.RgWsPublic
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RgWsPublicClient() : 
                base(RgWsPublicClient.GetDefaultBinding(), RgWsPublicClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RgWsPublicPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RgWsPublicClient(EndpointConfiguration endpointConfiguration) : 
                base(RgWsPublicClient.GetBindingForEndpoint(endpointConfiguration), RgWsPublicClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RgWsPublicClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RgWsPublicClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RgWsPublicClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RgWsPublicClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RgWsPublicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Indice.Features.GovGr.Proxies.Gsis.rgWsPublicAfmMethodResponse> rgWsPublicAfmMethodAsync(Indice.Features.GovGr.Proxies.Gsis.rgWsPublicAfmMethodRequest request)
        {
            return base.Channel.rgWsPublicAfmMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<Indice.Features.GovGr.Proxies.Gsis.rgWsPublicVersionInfoResponse> rgWsPublicVersionInfoAsync(Indice.Features.GovGr.Proxies.Gsis.rgWsPublicVersionInfoRequest request)
        {
            return base.Channel.rgWsPublicVersionInfoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RgWsPublicPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RgWsPublicPort))
            {
                return new System.ServiceModel.EndpointAddress("https://www1.gsis.gr/webtax2/wsgsis/RgWsPublic/RgWsPublicPort");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RgWsPublicClient.GetBindingForEndpoint(EndpointConfiguration.RgWsPublicPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RgWsPublicClient.GetEndpointAddress(EndpointConfiguration.RgWsPublicPort);
        }
        
        public enum EndpointConfiguration
        {
            
            RgWsPublicPort,
        }
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member