using Indice.Services;

namespace Indice.Features.Identity.UI.Models;

/// <summary>Request model for the MFA login page.</summary>
public class MfaLoginInputModel
{
    /// <summary>The OTP code inserted by the user.</summary>
    public string? OtpCode { get; set; }
    /// <summary>Flag that indicates that the client performed the login should be persisted.</summary>
    public bool RememberClient { get; set; }
    /// <summary>Flag that indicates that the user performed the login should be persisted.</summary>
    public bool RememberMe { get; set; }
    /// <summary>Flag that indicates that the OTP code should be resent.</summary>
    public bool ResendOtp { get; set; }
    /// <summary>The return URL after the login is successful.</summary>
    public string? ReturnUrl { get; set; }
    /// <summary>Device id generated by the client.</summary>
    public string? DeviceId { get; set; }
    /// <summary>The user selected delivery channel for the OTP code.</summary>
    public TotpDeliveryChannel? SelectedDeliveryChannel { get; set; }
    /// <summary>The <c>Code</c> of the user-selected authentication method (e.g. <c>"Sms"</c>, <c>"AuthenticatorApp"</c>). Preferred over <see cref="SelectedDeliveryChannel"/> for picker disambiguation, since not every method has a delivery channel.</summary>
    public string? SelectedMethodCode { get; set; }
}
