version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /data/pg-admin
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.AspNetCore.Authentication.Apple
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.AspNetCore.Authentication.GovGr
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.AspNetCore.Builder
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.AspNetCore.EmbeddedUI
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.AspNetCore
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Common
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.EntityFrameworkCore
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Extensions.Configuration.Database
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Cases.App
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /src/Indice.Features.Cases.App
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Cases.AspNetCore
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Cases.Core
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Cases.Server
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Cases.UI
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Cases.Workflows
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.GovGr
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Identity.AdminUI.App
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /src/Indice.Features.Identity.AdminUI.App
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Identity.AdminUI
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Identity.Core
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Identity.Server
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Identity.SignInLogs
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Identity.UI
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /src/Indice.Features.Identity.UI
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Media.AspNetCore
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Messages.App
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /src/Indice.Features.Messages.App
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Messages.AspNetCore
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Messages.Core
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Messages.UI
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Messages.Worker.Azure
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Messages.Worker
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.MultiTenancy.AspNetCore
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Multitenancy.Core
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Multitenancy.Worker.Azure
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Risk.App
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /src/Indice.Features.Risk.App
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Risk.Core
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Risk.Server
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Features.Risk.UI
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Hosting
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Indice.Services
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Indice.AspNetCore.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Indice.AspNetCore.Views
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Indice.Common.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Indice.EcmaScript.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Indice.Features.Cases.AspNetCore.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Indice.Features.GovGr.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Indice.Features.Identity.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Indice.Features.Messages.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Indice.Features.Risk.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Indice.Services.Tests
    schedule:
      interval: daily
