//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indice.AspNetCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indice.AspNetCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s email is already confirmed..
        /// </summary>
        internal static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification code is {0}..
        /// </summary>
        internal static string EmailUpdateMessageBody {
            get {
                return ResourceManager.GetString("EmailUpdateMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account..
        /// </summary>
        internal static string EmailUpdateMessageSubject {
            get {
                return ResourceManager.GetString("EmailUpdateMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification code is {0}..
        /// </summary>
        internal static string ForgotPasswordMessageBody {
            get {
                return ResourceManager.GetString("ForgotPasswordMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        internal static string ForgotPasswordMessageSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain non latin characters..
        /// </summary>
        internal static string PasswordHasNonLatinChars {
            get {
                return ResourceManager.GetString("PasswordHasNonLatinChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is identical to your username..
        /// </summary>
        internal static string PasswordIdenticalToUserName {
            get {
                return ResourceManager.GetString("PasswordIdenticalToUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is very common to use..
        /// </summary>
        internal static string PasswordIsCommon {
            get {
                return ResourceManager.GetString("PasswordIsCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password has been used recently..
        /// </summary>
        internal static string PasswordRecentlyUsed {
            get {
                return ResourceManager.GetString("PasswordRecentlyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s phone number is already confirmed..
        /// </summary>
        internal static string PhoneNumberAlreadyConfirmed {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS verification code is {0}..
        /// </summary>
        internal static string PhoneNumberVerificationMessage {
            get {
                return ResourceManager.GetString("PhoneNumberVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has email &apos;{0}&apos;..
        /// </summary>
        internal static string UserAlreadyHasEmail {
            get {
                return ResourceManager.GetString("UserAlreadyHasEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has phone number &apos;{0}&apos;..
        /// </summary>
        internal static string UserAlreadyHasPhoneNumber {
            get {
                return ResourceManager.GetString("UserAlreadyHasPhoneNumber", resourceCulture);
            }
        }
    }
}
