<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PackageJsonName Condition="$(PackageJsonName) == ''">cases-app</PackageJsonName>
    <PackageJsonVersion Condition="$(PackageJsonVersion) == ''">1.0.0</PackageJsonVersion>
    <PackageJsonScriptsBuildTemplate Condition="$(PackageJsonScriptsBuildTemplate) == ''">ng build --build-optimizer --optimization --output-hashing none -c template</PackageJsonScriptsBuildTemplate>
    <PackageJsonScriptsBuild Condition="$(PackageJsonScriptsBuild) == ''">ng build --configuration production --buildOptimizer --optimization</PackageJsonScriptsBuild>
    <PackageJsonScriptsE2e Condition="$(PackageJsonScriptsE2e) == ''">ng e2e</PackageJsonScriptsE2e>
    <PackageJsonScriptsLint Condition="$(PackageJsonScriptsLint) == ''">ng lint</PackageJsonScriptsLint>
    <PackageJsonScriptsNg Condition="$(PackageJsonScriptsNg) == ''">ng</PackageJsonScriptsNg>
    <PackageJsonScriptsServe Condition="$(PackageJsonScriptsServe) == ''">ng serve</PackageJsonScriptsServe>
    <PackageJsonScriptsProdBuildDevOnpremises Condition="$(PackageJsonScriptsProdBuildDevOnpremises) == ''">ng build --configuration=on-premises-dev</PackageJsonScriptsProdBuildDevOnpremises>
    <PackageJsonPrivate Condition="$(PackageJsonPrivate) == ''">true</PackageJsonPrivate>
    <PackageJsonDependenciesAjsfExtendedCore Condition="$(PackageJsonDependenciesAjsfExtendedCore) == ''">0.7.6</PackageJsonDependenciesAjsfExtendedCore>
    <PackageJsonDependenciesAngularAnimations Condition="$(PackageJsonDependenciesAngularAnimations) == ''">17.3.12</PackageJsonDependenciesAngularAnimations>
    <PackageJsonDependenciesAngularCommon Condition="$(PackageJsonDependenciesAngularCommon) == ''">17.3.12</PackageJsonDependenciesAngularCommon>
    <PackageJsonDependenciesAngularCompiler Condition="$(PackageJsonDependenciesAngularCompiler) == ''">17.3.12</PackageJsonDependenciesAngularCompiler>
    <PackageJsonDependenciesAngularCore Condition="$(PackageJsonDependenciesAngularCore) == ''">17.3.12</PackageJsonDependenciesAngularCore>
    <PackageJsonDependenciesAngularForms Condition="$(PackageJsonDependenciesAngularForms) == ''">17.3.12</PackageJsonDependenciesAngularForms>
    <PackageJsonDependenciesAngularPlatformBrowser Condition="$(PackageJsonDependenciesAngularPlatformBrowser) == ''">17.3.12</PackageJsonDependenciesAngularPlatformBrowser>
    <PackageJsonDependenciesAngularPlatformBrowserDynamic Condition="$(PackageJsonDependenciesAngularPlatformBrowserDynamic) == ''">17.3.12</PackageJsonDependenciesAngularPlatformBrowserDynamic>
    <PackageJsonDependenciesAngularRouter Condition="$(PackageJsonDependenciesAngularRouter) == ''">17.3.12</PackageJsonDependenciesAngularRouter>
    <PackageJsonDependenciesIndiceNgAuth Condition="$(PackageJsonDependenciesIndiceNgAuth) == ''">0.3.5</PackageJsonDependenciesIndiceNgAuth>
    <PackageJsonDependenciesIndiceNgComponents Condition="$(PackageJsonDependenciesIndiceNgComponents) == ''">0.3.12</PackageJsonDependenciesIndiceNgComponents>
    <PackageJsonDependenciesNgxTranslateCore Condition="$(PackageJsonDependenciesNgxTranslateCore) == ''">^15.0.0</PackageJsonDependenciesNgxTranslateCore>
    <PackageJsonDependenciesNgxTranslateHttpLoader Condition="$(PackageJsonDependenciesNgxTranslateHttpLoader) == ''">^8.0.0</PackageJsonDependenciesNgxTranslateHttpLoader>
    <PackageJsonDependenciesChartJs Condition="$(PackageJsonDependenciesChartJs) == ''">^4.2.0</PackageJsonDependenciesChartJs>
    <PackageJsonDependenciesF Condition="$(PackageJsonDependenciesF) == ''">^1.4.0</PackageJsonDependenciesF>
    <PackageJsonDependenciesFileSaver Condition="$(PackageJsonDependenciesFileSaver) == ''">^2.0.5</PackageJsonDependenciesFileSaver>
    <PackageJsonDependenciesLodash Condition="$(PackageJsonDependenciesLodash) == ''">^4.17.21</PackageJsonDependenciesLodash>
    <PackageJsonDependenciesMoment Condition="$(PackageJsonDependenciesMoment) == ''">~2.30.1</PackageJsonDependenciesMoment>
    <PackageJsonDependenciesNgxMask Condition="$(PackageJsonDependenciesNgxMask) == ''">^17.0.8</PackageJsonDependenciesNgxMask>
    <PackageJsonDependenciesNgxProgressbar Condition="$(PackageJsonDependenciesNgxProgressbar) == ''">^13.0.0</PackageJsonDependenciesNgxProgressbar>
    <PackageJsonDependenciesNgxQuill Condition="$(PackageJsonDependenciesNgxQuill) == ''">^25.3.2</PackageJsonDependenciesNgxQuill>
    <PackageJsonDependenciesOidcClientTs Condition="$(PackageJsonDependenciesOidcClientTs) == ''">3.1.0</PackageJsonDependenciesOidcClientTs>
    <PackageJsonDependenciesRxjs Condition="$(PackageJsonDependenciesRxjs) == ''">^7.8.1</PackageJsonDependenciesRxjs>
    <PackageJsonDependenciesTslib Condition="$(PackageJsonDependenciesTslib) == ''">^2.6.2</PackageJsonDependenciesTslib>
    <PackageJsonDependenciesZoneJs Condition="$(PackageJsonDependenciesZoneJs) == ''">0.14.6</PackageJsonDependenciesZoneJs>
    <PackageJsonDevdependenciesAngularDevkitBuildAngular Condition="$(PackageJsonDevdependenciesAngularDevkitBuildAngular) == ''">17.3.11</PackageJsonDevdependenciesAngularDevkitBuildAngular>
    <PackageJsonDevdependenciesAngularCli Condition="$(PackageJsonDevdependenciesAngularCli) == ''">17.3.11</PackageJsonDevdependenciesAngularCli>
    <PackageJsonDevdependenciesAngularCompilerCli Condition="$(PackageJsonDevdependenciesAngularCompilerCli) == ''">17.3.12</PackageJsonDevdependenciesAngularCompilerCli>
    <PackageJsonDevdependenciesTailwindcssAspectRatio Condition="$(PackageJsonDevdependenciesTailwindcssAspectRatio) == ''">0.4.2</PackageJsonDevdependenciesTailwindcssAspectRatio>
    <PackageJsonDevdependenciesTailwindcssForms Condition="$(PackageJsonDevdependenciesTailwindcssForms) == ''">0.5.10</PackageJsonDevdependenciesTailwindcssForms>
    <PackageJsonDevdependenciesTailwindcssTypography Condition="$(PackageJsonDevdependenciesTailwindcssTypography) == ''">0.5.15</PackageJsonDevdependenciesTailwindcssTypography>
    <PackageJsonDevdependenciesTypesFileSaver Condition="$(PackageJsonDevdependenciesTypesFileSaver) == ''">^2.0.5</PackageJsonDevdependenciesTypesFileSaver>
    <PackageJsonDevdependenciesTypesJasmine Condition="$(PackageJsonDevdependenciesTypesJasmine) == ''">5.1.5</PackageJsonDevdependenciesTypesJasmine>
    <PackageJsonDevdependenciesTypesLodash Condition="$(PackageJsonDevdependenciesTypesLodash) == ''">^4.14.180</PackageJsonDevdependenciesTypesLodash>
    <PackageJsonDevdependenciesTypesQuill Condition="$(PackageJsonDevdependenciesTypesQuill) == ''">^1.3.10</PackageJsonDevdependenciesTypesQuill>
    <PackageJsonDevdependenciesJasmineCore Condition="$(PackageJsonDevdependenciesJasmineCore) == ''">3.99.1</PackageJsonDevdependenciesJasmineCore>
    <PackageJsonDevdependenciesKarma Condition="$(PackageJsonDevdependenciesKarma) == ''">6.4.4</PackageJsonDevdependenciesKarma>
    <PackageJsonDevdependenciesKarmaChromeLauncher Condition="$(PackageJsonDevdependenciesKarmaChromeLauncher) == ''">3.1.0</PackageJsonDevdependenciesKarmaChromeLauncher>
    <PackageJsonDevdependenciesKarmaCoverage Condition="$(PackageJsonDevdependenciesKarmaCoverage) == ''">2.0.3</PackageJsonDevdependenciesKarmaCoverage>
    <PackageJsonDevdependenciesKarmaJasmine Condition="$(PackageJsonDevdependenciesKarmaJasmine) == ''">4.0.0</PackageJsonDevdependenciesKarmaJasmine>
    <PackageJsonDevdependenciesKarmaJasmineHtmlReporter Condition="$(PackageJsonDevdependenciesKarmaJasmineHtmlReporter) == ''">1.7.0</PackageJsonDevdependenciesKarmaJasmineHtmlReporter>
    <PackageJsonDevdependenciesTailwindcss Condition="$(PackageJsonDevdependenciesTailwindcss) == ''">3.4.17</PackageJsonDevdependenciesTailwindcss>
    <PackageJsonDevdependenciesTypescript Condition="$(PackageJsonDevdependenciesTypescript) == ''">5.4.5</PackageJsonDevdependenciesTypescript>
  </PropertyGroup>
</Project>