<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PackageJsonName Condition="$(PackageJsonName) == ''">risks-app</PackageJsonName>
    <PackageJsonVersion Condition="$(PackageJsonVersion) == ''">1.0.0</PackageJsonVersion>
    <PackageJsonScriptsBuildTemplate Condition="$(PackageJsonScriptsBuildTemplate) == ''">ng build --output-hashing none --configuration template</PackageJsonScriptsBuildTemplate>
    <PackageJsonScriptsBuild Condition="$(PackageJsonScriptsBuild) == ''">ng build --configuration production</PackageJsonScriptsBuild>
    <PackageJsonScriptsE2e Condition="$(PackageJsonScriptsE2e) == ''">ng e2e</PackageJsonScriptsE2e>
    <PackageJsonScriptsLint Condition="$(PackageJsonScriptsLint) == ''">ng lint</PackageJsonScriptsLint>
    <PackageJsonScriptsNg Condition="$(PackageJsonScriptsNg) == ''">ng</PackageJsonScriptsNg>
    <PackageJsonScriptsStart Condition="$(PackageJsonScriptsStart) == ''">ng serve</PackageJsonScriptsStart>
    <PackageJsonPrivate Condition="$(PackageJsonPrivate) == ''">true</PackageJsonPrivate>
    <PackageJsonDependenciesAngularAnimations Condition="$(PackageJsonDependenciesAngularAnimations) == ''">20.3.18</PackageJsonDependenciesAngularAnimations>
    <PackageJsonDependenciesAngularCommon Condition="$(PackageJsonDependenciesAngularCommon) == ''">20.3.18</PackageJsonDependenciesAngularCommon>
    <PackageJsonDependenciesAngularCompiler Condition="$(PackageJsonDependenciesAngularCompiler) == ''">20.3.18</PackageJsonDependenciesAngularCompiler>
    <PackageJsonDependenciesAngularCore Condition="$(PackageJsonDependenciesAngularCore) == ''">20.3.18</PackageJsonDependenciesAngularCore>
    <PackageJsonDependenciesAngularForms Condition="$(PackageJsonDependenciesAngularForms) == ''">20.3.18</PackageJsonDependenciesAngularForms>
    <PackageJsonDependenciesAngularPlatformBrowser Condition="$(PackageJsonDependenciesAngularPlatformBrowser) == ''">20.3.18</PackageJsonDependenciesAngularPlatformBrowser>
    <PackageJsonDependenciesAngularPlatformBrowserDynamic Condition="$(PackageJsonDependenciesAngularPlatformBrowserDynamic) == ''">20.3.18</PackageJsonDependenciesAngularPlatformBrowserDynamic>
    <PackageJsonDependenciesAngularRouter Condition="$(PackageJsonDependenciesAngularRouter) == ''">20.3.18</PackageJsonDependenciesAngularRouter>
    <PackageJsonDependenciesIndiceNgAuth Condition="$(PackageJsonDependenciesIndiceNgAuth) == ''">0.5.1</PackageJsonDependenciesIndiceNgAuth>
    <PackageJsonDependenciesIndiceNgComponents Condition="$(PackageJsonDependenciesIndiceNgComponents) == ''">0.5.0</PackageJsonDependenciesIndiceNgComponents>
    <PackageJsonDependenciesF Condition="$(PackageJsonDependenciesF) == ''">^1.4.0</PackageJsonDependenciesF>
    <PackageJsonDependenciesFileSaver Condition="$(PackageJsonDependenciesFileSaver) == ''">^2.0.5</PackageJsonDependenciesFileSaver>
    <PackageJsonDependenciesLodash Condition="$(PackageJsonDependenciesLodash) == ''">^4.17.21</PackageJsonDependenciesLodash>
    <PackageJsonDependenciesMoment Condition="$(PackageJsonDependenciesMoment) == ''">~2.30.1</PackageJsonDependenciesMoment>
    <PackageJsonDependenciesNgxJsonViewer Condition="$(PackageJsonDependenciesNgxJsonViewer) == ''">^3.2.1</PackageJsonDependenciesNgxJsonViewer>
    <PackageJsonDependenciesNgxMask Condition="$(PackageJsonDependenciesNgxMask) == ''">~12.0.0</PackageJsonDependenciesNgxMask>
    <PackageJsonDependenciesOidcClientTs Condition="$(PackageJsonDependenciesOidcClientTs) == ''">3.1.0</PackageJsonDependenciesOidcClientTs>
    <PackageJsonDependenciesRxjs Condition="$(PackageJsonDependenciesRxjs) == ''">7.8.2</PackageJsonDependenciesRxjs>
    <PackageJsonDependenciesTslib Condition="$(PackageJsonDependenciesTslib) == ''">^2.8.1</PackageJsonDependenciesTslib>
    <PackageJsonDependenciesZoneJs Condition="$(PackageJsonDependenciesZoneJs) == ''">0.15.1</PackageJsonDependenciesZoneJs>
    <PackageJsonDevdependenciesAngularBuild Condition="$(PackageJsonDevdependenciesAngularBuild) == ''">20.3.20</PackageJsonDevdependenciesAngularBuild>
    <PackageJsonDevdependenciesAngularCli Condition="$(PackageJsonDevdependenciesAngularCli) == ''">20.3.20</PackageJsonDevdependenciesAngularCli>
    <PackageJsonDevdependenciesAngularCompilerCli Condition="$(PackageJsonDevdependenciesAngularCompilerCli) == ''">20.3.18</PackageJsonDevdependenciesAngularCompilerCli>
    <PackageJsonDevdependenciesAngularLanguageService Condition="$(PackageJsonDevdependenciesAngularLanguageService) == ''">20.3.18</PackageJsonDevdependenciesAngularLanguageService>
    <PackageJsonDevdependenciesTailwindcssAspectRatio Condition="$(PackageJsonDevdependenciesTailwindcssAspectRatio) == ''">^0.4.2</PackageJsonDevdependenciesTailwindcssAspectRatio>
    <PackageJsonDevdependenciesTailwindcssForms Condition="$(PackageJsonDevdependenciesTailwindcssForms) == ''">^0.5.11</PackageJsonDevdependenciesTailwindcssForms>
    <PackageJsonDevdependenciesTailwindcssPostcss Condition="$(PackageJsonDevdependenciesTailwindcssPostcss) == ''">^4.1.14</PackageJsonDevdependenciesTailwindcssPostcss>
    <PackageJsonDevdependenciesTailwindcssTypography Condition="$(PackageJsonDevdependenciesTailwindcssTypography) == ''">^0.5.19</PackageJsonDevdependenciesTailwindcssTypography>
    <PackageJsonDevdependenciesTypesFileSaver Condition="$(PackageJsonDevdependenciesTypesFileSaver) == ''">2.0.7</PackageJsonDevdependenciesTypesFileSaver>
    <PackageJsonDevdependenciesTypesLodash Condition="$(PackageJsonDevdependenciesTypesLodash) == ''">^4.14.180</PackageJsonDevdependenciesTypesLodash>
    <PackageJsonDevdependenciesAutoprefixer Condition="$(PackageJsonDevdependenciesAutoprefixer) == ''">^10.4.19</PackageJsonDevdependenciesAutoprefixer>
    <PackageJsonDevdependenciesEslint Condition="$(PackageJsonDevdependenciesEslint) == ''">^9.3.0</PackageJsonDevdependenciesEslint>
    <PackageJsonDevdependenciesPostcss Condition="$(PackageJsonDevdependenciesPostcss) == ''">^8.5.6</PackageJsonDevdependenciesPostcss>
    <PackageJsonDevdependenciesTailwindcss Condition="$(PackageJsonDevdependenciesTailwindcss) == ''">4.1.16</PackageJsonDevdependenciesTailwindcss>
    <PackageJsonDevdependenciesTypescript Condition="$(PackageJsonDevdependenciesTypescript) == ''">5.8.3</PackageJsonDevdependenciesTypescript>
  </PropertyGroup>
</Project>