<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>Indice</RootNamespace>
    <VersionPrefix>$(VersionPrefixCore)</VersionPrefix>
  </PropertyGroup>
  <PropertyGroup Label="Package">
    <PackageTags>AspNet;GeoLocationResolver;Utilities</PackageTags>
    <PackageReleaseNotes></PackageReleaseNotes>
  </PropertyGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="GeoLite2\GeoLite2-City.mmdb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="GeoLite2\GeoLite2-Country.mmdb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Indice.Common" Version="$(VersionPrefixCore)-*" />
    <PackageReference Include="MaxMind.GeoIP2" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Indice.Common\Indice.Common.csproj" />
  </ItemGroup>
</Project>
