//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indice.TimeZones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ZoneInfoTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZoneInfoTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indice.TimeZones.ZoneInfoTranslations", typeof(ZoneInfoTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:30) Kabul.
        /// </summary>
        internal static string Afghanistan_Standard_Time {
            get {
                return ResourceManager.GetString("Afghanistan Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Cairo.
        /// </summary>
        internal static string Africa_Cairo {
            get {
                return ResourceManager.GetString("Africa/Cairo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Casablanca.
        /// </summary>
        internal static string Africa_Casablanca {
            get {
                return ResourceManager.GetString("Africa/Casablanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Harare, Pretoria.
        /// </summary>
        internal static string Africa_Johannesburg {
            get {
                return ResourceManager.GetString("Africa/Johannesburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Juba.
        /// </summary>
        internal static string Africa_Juba {
            get {
                return ResourceManager.GetString("Africa/Juba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Khartoum.
        /// </summary>
        internal static string Africa_Khartoum {
            get {
                return ResourceManager.GetString("Africa/Khartoum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) West Central Africa.
        /// </summary>
        internal static string Africa_Lagos {
            get {
                return ResourceManager.GetString("Africa/Lagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Nairobi.
        /// </summary>
        internal static string Africa_Nairobi {
            get {
                return ResourceManager.GetString("Africa/Nairobi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+00:00) Sao Tome.
        /// </summary>
        internal static string Africa_Sao_Tome {
            get {
                return ResourceManager.GetString("Africa/Sao_Tome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Tripoli.
        /// </summary>
        internal static string Africa_Tripoli {
            get {
                return ResourceManager.GetString("Africa/Tripoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Windhoek.
        /// </summary>
        internal static string Africa_Windhoek {
            get {
                return ResourceManager.GetString("Africa/Windhoek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-09:00) Alaska.
        /// </summary>
        internal static string Alaskan_Standard_Time {
            get {
                return ResourceManager.GetString("Alaskan Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-10:00) Aleutian Islands.
        /// </summary>
        internal static string Aleutian_Standard_Time {
            get {
                return ResourceManager.GetString("Aleutian Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Barnaul, Gorno-Altaysk.
        /// </summary>
        internal static string Altai_Standard_Time {
            get {
                return ResourceManager.GetString("Altai Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-10:00) Aleutian Islands.
        /// </summary>
        internal static string America_Adak {
            get {
                return ResourceManager.GetString("America/Adak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-09:00) Alaska.
        /// </summary>
        internal static string America_Anchorage {
            get {
                return ResourceManager.GetString("America/Anchorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Araguaina.
        /// </summary>
        internal static string America_Araguaina {
            get {
                return ResourceManager.GetString("America/Araguaina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Asuncion.
        /// </summary>
        internal static string America_Asuncion {
            get {
                return ResourceManager.GetString("America/Asuncion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Salvador.
        /// </summary>
        internal static string America_Bahia {
            get {
                return ResourceManager.GetString("America/Bahia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Bogota, Lima, Quito, Rio Branco.
        /// </summary>
        internal static string America_Bogota {
            get {
                return ResourceManager.GetString("America/Bogota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) City of Buenos Aires.
        /// </summary>
        internal static string America_Buenos_Aires {
            get {
                return ResourceManager.GetString("America/Buenos_Aires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Chetumal.
        /// </summary>
        internal static string America_Cancun {
            get {
                return ResourceManager.GetString("America/Cancun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Caracas.
        /// </summary>
        internal static string America_Caracas {
            get {
                return ResourceManager.GetString("America/Caracas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Cayenne, Fortaleza.
        /// </summary>
        internal static string America_Cayenne {
            get {
                return ResourceManager.GetString("America/Cayenne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Central Time (US &amp; Canada).
        /// </summary>
        internal static string America_Chicago {
            get {
                return ResourceManager.GetString("America/Chicago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) La Paz, Mazatlan.
        /// </summary>
        internal static string America_Chihuahua {
            get {
                return ResourceManager.GetString("America/Chihuahua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Cuiaba.
        /// </summary>
        internal static string America_Cuiaba {
            get {
                return ResourceManager.GetString("America/Cuiaba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Mountain Time (US &amp; Canada).
        /// </summary>
        internal static string America_Denver {
            get {
                return ResourceManager.GetString("America/Denver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-02:00) Greenland.
        /// </summary>
        internal static string America_Godthab {
            get {
                return ResourceManager.GetString("America/Godthab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Turks and Caicos.
        /// </summary>
        internal static string America_Grand_Turk {
            get {
                return ResourceManager.GetString("America/Grand_Turk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Central America.
        /// </summary>
        internal static string America_Guatemala {
            get {
                return ResourceManager.GetString("America/Guatemala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Atlantic Time (Canada).
        /// </summary>
        internal static string America_Halifax {
            get {
                return ResourceManager.GetString("America/Halifax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Havana.
        /// </summary>
        internal static string America_Havana {
            get {
                return ResourceManager.GetString("America/Havana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Indiana (East).
        /// </summary>
        internal static string America_Indianapolis {
            get {
                return ResourceManager.GetString("America/Indianapolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Georgetown, La Paz, Manaus, San Juan.
        /// </summary>
        internal static string America_La_Paz {
            get {
                return ResourceManager.GetString("America/La_Paz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-08:00) Pacific Time (US &amp; Canada).
        /// </summary>
        internal static string America_Los_Angeles {
            get {
                return ResourceManager.GetString("America/Los_Angeles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Guadalajara, Mexico City, Monterrey.
        /// </summary>
        internal static string America_Mexico_City {
            get {
                return ResourceManager.GetString("America/Mexico_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Saint Pierre and Miquelon.
        /// </summary>
        internal static string America_Miquelon {
            get {
                return ResourceManager.GetString("America/Miquelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Montevideo.
        /// </summary>
        internal static string America_Montevideo {
            get {
                return ResourceManager.GetString("America/Montevideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Eastern Time (US &amp; Canada).
        /// </summary>
        internal static string America_New_York {
            get {
                return ResourceManager.GetString("America/New_York", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Arizona.
        /// </summary>
        internal static string America_Phoenix {
            get {
                return ResourceManager.GetString("America/Phoenix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Haiti.
        /// </summary>
        internal static string America_Port_au_Prince {
            get {
                return ResourceManager.GetString("America/Port-au-Prince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Punta Arenas.
        /// </summary>
        internal static string America_Punta_Arenas {
            get {
                return ResourceManager.GetString("America/Punta_Arenas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Saskatchewan.
        /// </summary>
        internal static string America_Regina {
            get {
                return ResourceManager.GetString("America/Regina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Santiago.
        /// </summary>
        internal static string America_Santiago {
            get {
                return ResourceManager.GetString("America/Santiago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Brasilia.
        /// </summary>
        internal static string America_Sao_Paulo {
            get {
                return ResourceManager.GetString("America/Sao_Paulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:30) Newfoundland.
        /// </summary>
        internal static string America_St_Johns {
            get {
                return ResourceManager.GetString("America/St_Johns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-08:00) Baja California.
        /// </summary>
        internal static string America_Tijuana {
            get {
                return ResourceManager.GetString("America/Tijuana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Yukon.
        /// </summary>
        internal static string America_Whitehorse {
            get {
                return ResourceManager.GetString("America/Whitehorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Kuwait, Riyadh.
        /// </summary>
        internal static string Arab_Standard_Time {
            get {
                return ResourceManager.GetString("Arab Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Abu Dhabi, Muscat.
        /// </summary>
        internal static string Arabian_Standard_Time {
            get {
                return ResourceManager.GetString("Arabian Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Baghdad.
        /// </summary>
        internal static string Arabic_Standard_Time {
            get {
                return ResourceManager.GetString("Arabic Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) City of Buenos Aires.
        /// </summary>
        internal static string Argentina_Standard_Time {
            get {
                return ResourceManager.GetString("Argentina Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Bishkek.
        /// </summary>
        internal static string Asia_Almaty {
            get {
                return ResourceManager.GetString("Asia/Almaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Amman.
        /// </summary>
        internal static string Asia_Amman {
            get {
                return ResourceManager.GetString("Asia/Amman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Baghdad.
        /// </summary>
        internal static string Asia_Baghdad {
            get {
                return ResourceManager.GetString("Asia/Baghdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Baku.
        /// </summary>
        internal static string Asia_Baku {
            get {
                return ResourceManager.GetString("Asia/Baku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Bangkok, Hanoi, Jakarta.
        /// </summary>
        internal static string Asia_Bangkok {
            get {
                return ResourceManager.GetString("Asia/Bangkok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Barnaul, Gorno-Altaysk.
        /// </summary>
        internal static string Asia_Barnaul {
            get {
                return ResourceManager.GetString("Asia/Barnaul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Beirut.
        /// </summary>
        internal static string Asia_Beirut {
            get {
                return ResourceManager.GetString("Asia/Beirut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi.
        /// </summary>
        internal static string Asia_Calcutta {
            get {
                return ResourceManager.GetString("Asia/Calcutta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Chita.
        /// </summary>
        internal static string Asia_Chita {
            get {
                return ResourceManager.GetString("Asia/Chita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:30) Sri Jayawardenepura.
        /// </summary>
        internal static string Asia_Colombo {
            get {
                return ResourceManager.GetString("Asia/Colombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Damascus.
        /// </summary>
        internal static string Asia_Damascus {
            get {
                return ResourceManager.GetString("Asia/Damascus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Dhaka.
        /// </summary>
        internal static string Asia_Dhaka {
            get {
                return ResourceManager.GetString("Asia/Dhaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Abu Dhabi, Muscat.
        /// </summary>
        internal static string Asia_Dubai {
            get {
                return ResourceManager.GetString("Asia/Dubai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Gaza, Hebron.
        /// </summary>
        internal static string Asia_Hebron {
            get {
                return ResourceManager.GetString("Asia/Hebron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Hovd.
        /// </summary>
        internal static string Asia_Hovd {
            get {
                return ResourceManager.GetString("Asia/Hovd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Irkutsk.
        /// </summary>
        internal static string Asia_Irkutsk {
            get {
                return ResourceManager.GetString("Asia/Irkutsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Jerusalem.
        /// </summary>
        internal static string Asia_Jerusalem {
            get {
                return ResourceManager.GetString("Asia/Jerusalem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:30) Kabul.
        /// </summary>
        internal static string Asia_Kabul {
            get {
                return ResourceManager.GetString("Asia/Kabul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky.
        /// </summary>
        internal static string Asia_Kamchatka {
            get {
                return ResourceManager.GetString("Asia/Kamchatka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Islamabad, Karachi.
        /// </summary>
        internal static string Asia_Karachi {
            get {
                return ResourceManager.GetString("Asia/Karachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:45) Kathmandu.
        /// </summary>
        internal static string Asia_Katmandu {
            get {
                return ResourceManager.GetString("Asia/Katmandu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Krasnoyarsk.
        /// </summary>
        internal static string Asia_Krasnoyarsk {
            get {
                return ResourceManager.GetString("Asia/Krasnoyarsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Magadan.
        /// </summary>
        internal static string Asia_Magadan {
            get {
                return ResourceManager.GetString("Asia/Magadan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Novosibirsk.
        /// </summary>
        internal static string Asia_Novosibirsk {
            get {
                return ResourceManager.GetString("Asia/Novosibirsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Omsk.
        /// </summary>
        internal static string Asia_Omsk {
            get {
                return ResourceManager.GetString("Asia/Omsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Pyongyang.
        /// </summary>
        internal static string Asia_Pyongyang {
            get {
                return ResourceManager.GetString("Asia/Pyongyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Astana.
        /// </summary>
        internal static string Asia_Qyzylorda {
            get {
                return ResourceManager.GetString("Asia/Qyzylorda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:30) Yangon (Rangoon).
        /// </summary>
        internal static string Asia_Rangoon {
            get {
                return ResourceManager.GetString("Asia/Rangoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Kuwait, Riyadh.
        /// </summary>
        internal static string Asia_Riyadh {
            get {
                return ResourceManager.GetString("Asia/Riyadh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Sakhalin.
        /// </summary>
        internal static string Asia_Sakhalin {
            get {
                return ResourceManager.GetString("Asia/Sakhalin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Seoul.
        /// </summary>
        internal static string Asia_Seoul {
            get {
                return ResourceManager.GetString("Asia/Seoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi.
        /// </summary>
        internal static string Asia_Shanghai {
            get {
                return ResourceManager.GetString("Asia/Shanghai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Kuala Lumpur, Singapore.
        /// </summary>
        internal static string Asia_Singapore {
            get {
                return ResourceManager.GetString("Asia/Singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Chokurdakh.
        /// </summary>
        internal static string Asia_Srednekolymsk {
            get {
                return ResourceManager.GetString("Asia/Srednekolymsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Taipei.
        /// </summary>
        internal static string Asia_Taipei {
            get {
                return ResourceManager.GetString("Asia/Taipei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Ashgabat, Tashkent.
        /// </summary>
        internal static string Asia_Tashkent {
            get {
                return ResourceManager.GetString("Asia/Tashkent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Tbilisi.
        /// </summary>
        internal static string Asia_Tbilisi {
            get {
                return ResourceManager.GetString("Asia/Tbilisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:30) Tehran.
        /// </summary>
        internal static string Asia_Tehran {
            get {
                return ResourceManager.GetString("Asia/Tehran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Osaka, Sapporo, Tokyo.
        /// </summary>
        internal static string Asia_Tokyo {
            get {
                return ResourceManager.GetString("Asia/Tokyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Tomsk.
        /// </summary>
        internal static string Asia_Tomsk {
            get {
                return ResourceManager.GetString("Asia/Tomsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Ulaanbaatar.
        /// </summary>
        internal static string Asia_Ulaanbaatar {
            get {
                return ResourceManager.GetString("Asia/Ulaanbaatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Vladivostok.
        /// </summary>
        internal static string Asia_Vladivostok {
            get {
                return ResourceManager.GetString("Asia/Vladivostok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Yakutsk.
        /// </summary>
        internal static string Asia_Yakutsk {
            get {
                return ResourceManager.GetString("Asia/Yakutsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Ekaterinburg.
        /// </summary>
        internal static string Asia_Yekaterinburg {
            get {
                return ResourceManager.GetString("Asia/Yekaterinburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Yerevan.
        /// </summary>
        internal static string Asia_Yerevan {
            get {
                return ResourceManager.GetString("Asia/Yerevan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Astrakhan, Ulyanovsk.
        /// </summary>
        internal static string Astrakhan_Standard_Time {
            get {
                return ResourceManager.GetString("Astrakhan Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-01:00) Azores.
        /// </summary>
        internal static string Atlantic_Azores {
            get {
                return ResourceManager.GetString("Atlantic/Azores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-01:00) Cabo Verde Is..
        /// </summary>
        internal static string Atlantic_Cape_Verde {
            get {
                return ResourceManager.GetString("Atlantic/Cape_Verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+00:00) Monrovia, Reykjavik.
        /// </summary>
        internal static string Atlantic_Reykjavik {
            get {
                return ResourceManager.GetString("Atlantic/Reykjavik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Atlantic Time (Canada).
        /// </summary>
        internal static string Atlantic_Standard_Time {
            get {
                return ResourceManager.GetString("Atlantic Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:30) Darwin.
        /// </summary>
        internal static string AUS_Central_Standard_Time {
            get {
                return ResourceManager.GetString("AUS Central Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:45) Eucla.
        /// </summary>
        internal static string Aus_Central_W__Standard_Time {
            get {
                return ResourceManager.GetString("Aus Central W. Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Canberra, Melbourne, Sydney.
        /// </summary>
        internal static string AUS_Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("AUS Eastern Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:30) Adelaide.
        /// </summary>
        internal static string Australia_Adelaide {
            get {
                return ResourceManager.GetString("Australia/Adelaide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Brisbane.
        /// </summary>
        internal static string Australia_Brisbane {
            get {
                return ResourceManager.GetString("Australia/Brisbane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:30) Darwin.
        /// </summary>
        internal static string Australia_Darwin {
            get {
                return ResourceManager.GetString("Australia/Darwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:45) Eucla.
        /// </summary>
        internal static string Australia_Eucla {
            get {
                return ResourceManager.GetString("Australia/Eucla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Hobart.
        /// </summary>
        internal static string Australia_Hobart {
            get {
                return ResourceManager.GetString("Australia/Hobart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:30) Lord Howe Island.
        /// </summary>
        internal static string Australia_Lord_Howe {
            get {
                return ResourceManager.GetString("Australia/Lord_Howe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Perth.
        /// </summary>
        internal static string Australia_Perth {
            get {
                return ResourceManager.GetString("Australia/Perth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Canberra, Melbourne, Sydney.
        /// </summary>
        internal static string Australia_Sydney {
            get {
                return ResourceManager.GetString("Australia/Sydney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Baku.
        /// </summary>
        internal static string Azerbaijan_Standard_Time {
            get {
                return ResourceManager.GetString("Azerbaijan Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-01:00) Azores.
        /// </summary>
        internal static string Azores_Standard_Time {
            get {
                return ResourceManager.GetString("Azores Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Salvador.
        /// </summary>
        internal static string Bahia_Standard_Time {
            get {
                return ResourceManager.GetString("Bahia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Dhaka.
        /// </summary>
        internal static string Bangladesh_Standard_Time {
            get {
                return ResourceManager.GetString("Bangladesh Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Minsk.
        /// </summary>
        internal static string Belarus_Standard_Time {
            get {
                return ResourceManager.GetString("Belarus Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Bougainville Island.
        /// </summary>
        internal static string Bougainville_Standard_Time {
            get {
                return ResourceManager.GetString("Bougainville Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Saskatchewan.
        /// </summary>
        internal static string Canada_Central_Standard_Time {
            get {
                return ResourceManager.GetString("Canada Central Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-01:00) Cabo Verde Is..
        /// </summary>
        internal static string Cape_Verde_Standard_Time {
            get {
                return ResourceManager.GetString("Cape Verde Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Yerevan.
        /// </summary>
        internal static string Caucasus_Standard_Time {
            get {
                return ResourceManager.GetString("Caucasus Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:30) Adelaide.
        /// </summary>
        internal static string Cen__Australia_Standard_Time {
            get {
                return ResourceManager.GetString("Cen. Australia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Central America.
        /// </summary>
        internal static string Central_America_Standard_Time {
            get {
                return ResourceManager.GetString("Central America Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Bishkek.
        /// </summary>
        internal static string Central_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("Central Asia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Cuiaba.
        /// </summary>
        internal static string Central_Brazilian_Standard_Time {
            get {
                return ResourceManager.GetString("Central Brazilian Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague.
        /// </summary>
        internal static string Central_Europe_Standard_Time {
            get {
                return ResourceManager.GetString("Central Europe Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb.
        /// </summary>
        internal static string Central_European_Standard_Time {
            get {
                return ResourceManager.GetString("Central European Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Solomon Is., New Caledonia.
        /// </summary>
        internal static string Central_Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("Central Pacific Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Central Time (US &amp; Canada).
        /// </summary>
        internal static string Central_Standard_Time {
            get {
                return ResourceManager.GetString("Central Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Guadalajara, Mexico City, Monterrey.
        /// </summary>
        internal static string Central_Standard_Time__Mexico_ {
            get {
                return ResourceManager.GetString("Central Standard Time (Mexico)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:45) Chatham Islands.
        /// </summary>
        internal static string Chatham_Islands_Standard_Time {
            get {
                return ResourceManager.GetString("Chatham Islands Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi.
        /// </summary>
        internal static string China_Standard_Time {
            get {
                return ResourceManager.GetString("China Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Havana.
        /// </summary>
        internal static string Cuba_Standard_Time {
            get {
                return ResourceManager.GetString("Cuba Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-12:00) International Date Line West.
        /// </summary>
        internal static string Dateline_Standard_Time {
            get {
                return ResourceManager.GetString("Dateline Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Nairobi.
        /// </summary>
        internal static string E__Africa_Standard_Time {
            get {
                return ResourceManager.GetString("E. Africa Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Brisbane.
        /// </summary>
        internal static string E__Australia_Standard_Time {
            get {
                return ResourceManager.GetString("E. Australia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Chisinau.
        /// </summary>
        internal static string E__Europe_Standard_Time {
            get {
                return ResourceManager.GetString("E. Europe Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Brasilia.
        /// </summary>
        internal static string E__South_America_Standard_Time {
            get {
                return ResourceManager.GetString("E. South America Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Easter Island.
        /// </summary>
        internal static string Easter_Island_Standard_Time {
            get {
                return ResourceManager.GetString("Easter Island Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Eastern Time (US &amp; Canada).
        /// </summary>
        internal static string Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("Eastern Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Chetumal.
        /// </summary>
        internal static string Eastern_Standard_Time__Mexico_ {
            get {
                return ResourceManager.GetString("Eastern Standard Time (Mexico)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Cairo.
        /// </summary>
        internal static string Egypt_Standard_Time {
            get {
                return ResourceManager.GetString("Egypt Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Ekaterinburg.
        /// </summary>
        internal static string Ekaterinburg_Standard_Time {
            get {
                return ResourceManager.GetString("Ekaterinburg Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-11:00) Coordinated Universal Time-11.
        /// </summary>
        internal static string Etc_GMT_11 {
            get {
                return ResourceManager.GetString("Etc/GMT+11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+13:00) Coordinated Universal Time+13.
        /// </summary>
        internal static string Etc_GMT_13 {
            get {
                return ResourceManager.GetString("Etc/GMT-13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-02:00) Coordinated Universal Time-02.
        /// </summary>
        internal static string Etc_GMT_2 {
            get {
                return ResourceManager.GetString("Etc/GMT+2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-08:00) Coordinated Universal Time-08.
        /// </summary>
        internal static string Etc_GMT_8 {
            get {
                return ResourceManager.GetString("Etc/GMT+8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-09:00) Coordinated Universal Time-09.
        /// </summary>
        internal static string Etc_GMT_9 {
            get {
                return ResourceManager.GetString("Etc/GMT+9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC) Coordinated Universal Time.
        /// </summary>
        internal static string Etc_UTC {
            get {
                return ResourceManager.GetString("Etc/UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Astrakhan, Ulyanovsk.
        /// </summary>
        internal static string Europe_Astrakhan {
            get {
                return ResourceManager.GetString("Europe/Astrakhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna.
        /// </summary>
        internal static string Europe_Berlin {
            get {
                return ResourceManager.GetString("Europe/Berlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Athens, Bucharest.
        /// </summary>
        internal static string Europe_Bucharest {
            get {
                return ResourceManager.GetString("Europe/Bucharest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague.
        /// </summary>
        internal static string Europe_Budapest {
            get {
                return ResourceManager.GetString("Europe/Budapest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Chisinau.
        /// </summary>
        internal static string Europe_Chisinau {
            get {
                return ResourceManager.GetString("Europe/Chisinau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Istanbul.
        /// </summary>
        internal static string Europe_Istanbul {
            get {
                return ResourceManager.GetString("Europe/Istanbul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Kaliningrad.
        /// </summary>
        internal static string Europe_Kaliningrad {
            get {
                return ResourceManager.GetString("Europe/Kaliningrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius.
        /// </summary>
        internal static string Europe_Kiev {
            get {
                return ResourceManager.GetString("Europe/Kiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+00:00) Dublin, Edinburgh, Lisbon, London.
        /// </summary>
        internal static string Europe_London {
            get {
                return ResourceManager.GetString("Europe/London", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Minsk.
        /// </summary>
        internal static string Europe_Minsk {
            get {
                return ResourceManager.GetString("Europe/Minsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Moscow, St. Petersburg.
        /// </summary>
        internal static string Europe_Moscow {
            get {
                return ResourceManager.GetString("Europe/Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Brussels, Copenhagen, Madrid, Paris.
        /// </summary>
        internal static string Europe_Paris {
            get {
                return ResourceManager.GetString("Europe/Paris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Izhevsk, Samara.
        /// </summary>
        internal static string Europe_Samara {
            get {
                return ResourceManager.GetString("Europe/Samara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Saratov.
        /// </summary>
        internal static string Europe_Saratov {
            get {
                return ResourceManager.GetString("Europe/Saratov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Volgograd.
        /// </summary>
        internal static string Europe_Volgograd {
            get {
                return ResourceManager.GetString("Europe/Volgograd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb.
        /// </summary>
        internal static string Europe_Warsaw {
            get {
                return ResourceManager.GetString("Europe/Warsaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Fiji.
        /// </summary>
        internal static string Fiji_Standard_Time {
            get {
                return ResourceManager.GetString("Fiji Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius.
        /// </summary>
        internal static string FLE_Standard_Time {
            get {
                return ResourceManager.GetString("FLE Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Tbilisi.
        /// </summary>
        internal static string Georgian_Standard_Time {
            get {
                return ResourceManager.GetString("Georgian Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+00:00) Dublin, Edinburgh, Lisbon, London.
        /// </summary>
        internal static string GMT_Standard_Time {
            get {
                return ResourceManager.GetString("GMT Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-02:00) Greenland.
        /// </summary>
        internal static string Greenland_Standard_Time {
            get {
                return ResourceManager.GetString("Greenland Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+00:00) Monrovia, Reykjavik.
        /// </summary>
        internal static string Greenwich_Standard_Time {
            get {
                return ResourceManager.GetString("Greenwich Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Athens, Bucharest.
        /// </summary>
        internal static string GTB_Standard_Time {
            get {
                return ResourceManager.GetString("GTB Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Haiti.
        /// </summary>
        internal static string Haiti_Standard_Time {
            get {
                return ResourceManager.GetString("Haiti Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-10:00) Hawaii.
        /// </summary>
        internal static string Hawaiian_Standard_Time {
            get {
                return ResourceManager.GetString("Hawaiian Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi.
        /// </summary>
        internal static string India_Standard_Time {
            get {
                return ResourceManager.GetString("India Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Port Louis.
        /// </summary>
        internal static string Indian_Mauritius {
            get {
                return ResourceManager.GetString("Indian/Mauritius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:30) Tehran.
        /// </summary>
        internal static string Iran_Standard_Time {
            get {
                return ResourceManager.GetString("Iran Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Jerusalem.
        /// </summary>
        internal static string Israel_Standard_Time {
            get {
                return ResourceManager.GetString("Israel Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Amman.
        /// </summary>
        internal static string Jordan_Standard_Time {
            get {
                return ResourceManager.GetString("Jordan Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Kaliningrad.
        /// </summary>
        internal static string Kaliningrad_Standard_Time {
            get {
                return ResourceManager.GetString("Kaliningrad Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Petropavlovsk-Kamchatsky - Old.
        /// </summary>
        internal static string Kamchatka_Standard_Time {
            get {
                return ResourceManager.GetString("Kamchatka Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Seoul.
        /// </summary>
        internal static string Korea_Standard_Time {
            get {
                return ResourceManager.GetString("Korea Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Tripoli.
        /// </summary>
        internal static string Libya_Standard_Time {
            get {
                return ResourceManager.GetString("Libya Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+14:00) Kiritimati Island.
        /// </summary>
        internal static string Line_Islands_Standard_Time {
            get {
                return ResourceManager.GetString("Line Islands Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:30) Lord Howe Island.
        /// </summary>
        internal static string Lord_Howe_Standard_Time {
            get {
                return ResourceManager.GetString("Lord Howe Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Magadan.
        /// </summary>
        internal static string Magadan_Standard_Time {
            get {
                return ResourceManager.GetString("Magadan Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Punta Arenas.
        /// </summary>
        internal static string Magallanes_Standard_Time {
            get {
                return ResourceManager.GetString("Magallanes Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-09:30) Marquesas Islands.
        /// </summary>
        internal static string Marquesas_Standard_Time {
            get {
                return ResourceManager.GetString("Marquesas Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Port Louis.
        /// </summary>
        internal static string Mauritius_Standard_Time {
            get {
                return ResourceManager.GetString("Mauritius Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-02:00) Mid-Atlantic - Old.
        /// </summary>
        internal static string Mid_Atlantic_Standard_Time {
            get {
                return ResourceManager.GetString("Mid-Atlantic Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Beirut.
        /// </summary>
        internal static string Middle_East_Standard_Time {
            get {
                return ResourceManager.GetString("Middle East Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Montevideo.
        /// </summary>
        internal static string Montevideo_Standard_Time {
            get {
                return ResourceManager.GetString("Montevideo Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Casablanca.
        /// </summary>
        internal static string Morocco_Standard_Time {
            get {
                return ResourceManager.GetString("Morocco Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Mountain Time (US &amp; Canada).
        /// </summary>
        internal static string Mountain_Standard_Time {
            get {
                return ResourceManager.GetString("Mountain Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) La Paz, Mazatlan.
        /// </summary>
        internal static string Mountain_Standard_Time__Mexico_ {
            get {
                return ResourceManager.GetString("Mountain Standard Time (Mexico)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:30) Yangon (Rangoon).
        /// </summary>
        internal static string Myanmar_Standard_Time {
            get {
                return ResourceManager.GetString("Myanmar Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Novosibirsk.
        /// </summary>
        internal static string N__Central_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("N. Central Asia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Windhoek.
        /// </summary>
        internal static string Namibia_Standard_Time {
            get {
                return ResourceManager.GetString("Namibia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:45) Kathmandu.
        /// </summary>
        internal static string Nepal_Standard_Time {
            get {
                return ResourceManager.GetString("Nepal Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Auckland, Wellington.
        /// </summary>
        internal static string New_Zealand_Standard_Time {
            get {
                return ResourceManager.GetString("New Zealand Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:30) Newfoundland.
        /// </summary>
        internal static string Newfoundland_Standard_Time {
            get {
                return ResourceManager.GetString("Newfoundland Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Norfolk Island.
        /// </summary>
        internal static string Norfolk_Standard_Time {
            get {
                return ResourceManager.GetString("Norfolk Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Irkutsk.
        /// </summary>
        internal static string North_Asia_East_Standard_Time {
            get {
                return ResourceManager.GetString("North Asia East Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Krasnoyarsk.
        /// </summary>
        internal static string North_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("North Asia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Pyongyang.
        /// </summary>
        internal static string North_Korea_Standard_Time {
            get {
                return ResourceManager.GetString("North Korea Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Omsk.
        /// </summary>
        internal static string Omsk_Standard_Time {
            get {
                return ResourceManager.GetString("Omsk Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+13:00) Samoa.
        /// </summary>
        internal static string Pacific_Apia {
            get {
                return ResourceManager.GetString("Pacific/Apia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Auckland, Wellington.
        /// </summary>
        internal static string Pacific_Auckland {
            get {
                return ResourceManager.GetString("Pacific/Auckland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Bougainville Island.
        /// </summary>
        internal static string Pacific_Bougainville {
            get {
                return ResourceManager.GetString("Pacific/Bougainville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:45) Chatham Islands.
        /// </summary>
        internal static string Pacific_Chatham {
            get {
                return ResourceManager.GetString("Pacific/Chatham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Easter Island.
        /// </summary>
        internal static string Pacific_Easter {
            get {
                return ResourceManager.GetString("Pacific/Easter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Fiji.
        /// </summary>
        internal static string Pacific_Fiji {
            get {
                return ResourceManager.GetString("Pacific/Fiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Solomon Is., New Caledonia.
        /// </summary>
        internal static string Pacific_Guadalcanal {
            get {
                return ResourceManager.GetString("Pacific/Guadalcanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-10:00) Hawaii.
        /// </summary>
        internal static string Pacific_Honolulu {
            get {
                return ResourceManager.GetString("Pacific/Honolulu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+14:00) Kiritimati Island.
        /// </summary>
        internal static string Pacific_Kiritimati {
            get {
                return ResourceManager.GetString("Pacific/Kiritimati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-09:30) Marquesas Islands.
        /// </summary>
        internal static string Pacific_Marquesas {
            get {
                return ResourceManager.GetString("Pacific/Marquesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Norfolk Island.
        /// </summary>
        internal static string Pacific_Norfolk {
            get {
                return ResourceManager.GetString("Pacific/Norfolk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Guam, Port Moresby.
        /// </summary>
        internal static string Pacific_Port_Moresby {
            get {
                return ResourceManager.GetString("Pacific/Port_Moresby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Santiago.
        /// </summary>
        internal static string Pacific_SA_Standard_Time {
            get {
                return ResourceManager.GetString("Pacific SA Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-08:00) Pacific Time (US &amp; Canada).
        /// </summary>
        internal static string Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("Pacific Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-08:00) Baja California.
        /// </summary>
        internal static string Pacific_Standard_Time__Mexico_ {
            get {
                return ResourceManager.GetString("Pacific Standard Time (Mexico)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+13:00) Nuku&apos;alofa.
        /// </summary>
        internal static string Pacific_Tongatapu {
            get {
                return ResourceManager.GetString("Pacific/Tongatapu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Islamabad, Karachi.
        /// </summary>
        internal static string Pakistan_Standard_Time {
            get {
                return ResourceManager.GetString("Pakistan Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Asuncion.
        /// </summary>
        internal static string Paraguay_Standard_Time {
            get {
                return ResourceManager.GetString("Paraguay Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Astana.
        /// </summary>
        internal static string Qyzylorda_Standard_Time {
            get {
                return ResourceManager.GetString("Qyzylorda Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Brussels, Copenhagen, Madrid, Paris.
        /// </summary>
        internal static string Romance_Standard_Time {
            get {
                return ResourceManager.GetString("Romance Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Chokurdakh.
        /// </summary>
        internal static string Russia_Time_Zone_10 {
            get {
                return ResourceManager.GetString("Russia Time Zone 10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky.
        /// </summary>
        internal static string Russia_Time_Zone_11 {
            get {
                return ResourceManager.GetString("Russia Time Zone 11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Izhevsk, Samara.
        /// </summary>
        internal static string Russia_Time_Zone_3 {
            get {
                return ResourceManager.GetString("Russia Time Zone 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Moscow, St. Petersburg.
        /// </summary>
        internal static string Russian_Standard_Time {
            get {
                return ResourceManager.GetString("Russian Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Cayenne, Fortaleza.
        /// </summary>
        internal static string SA_Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("SA Eastern Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Bogota, Lima, Quito, Rio Branco.
        /// </summary>
        internal static string SA_Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("SA Pacific Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Georgetown, La Paz, Manaus, San Juan.
        /// </summary>
        internal static string SA_Western_Standard_Time {
            get {
                return ResourceManager.GetString("SA Western Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Saint Pierre and Miquelon.
        /// </summary>
        internal static string Saint_Pierre_Standard_Time {
            get {
                return ResourceManager.GetString("Saint Pierre Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Sakhalin.
        /// </summary>
        internal static string Sakhalin_Standard_Time {
            get {
                return ResourceManager.GetString("Sakhalin Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+13:00) Samoa.
        /// </summary>
        internal static string Samoa_Standard_Time {
            get {
                return ResourceManager.GetString("Samoa Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+00:00) Sao Tome.
        /// </summary>
        internal static string Sao_Tome_Standard_Time {
            get {
                return ResourceManager.GetString("Sao Tome Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Saratov.
        /// </summary>
        internal static string Saratov_Standard_Time {
            get {
                return ResourceManager.GetString("Saratov Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Bangkok, Hanoi, Jakarta.
        /// </summary>
        internal static string SE_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("SE Asia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Kuala Lumpur, Singapore.
        /// </summary>
        internal static string Singapore_Standard_Time {
            get {
                return ResourceManager.GetString("Singapore Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Harare, Pretoria.
        /// </summary>
        internal static string South_Africa_Standard_Time {
            get {
                return ResourceManager.GetString("South Africa Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Juba.
        /// </summary>
        internal static string South_Sudan_Standard_Time {
            get {
                return ResourceManager.GetString("South Sudan Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:30) Sri Jayawardenepura.
        /// </summary>
        internal static string Sri_Lanka_Standard_Time {
            get {
                return ResourceManager.GetString("Sri Lanka Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Khartoum.
        /// </summary>
        internal static string Sudan_Standard_Time {
            get {
                return ResourceManager.GetString("Sudan Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Damascus.
        /// </summary>
        internal static string Syria_Standard_Time {
            get {
                return ResourceManager.GetString("Syria Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Taipei.
        /// </summary>
        internal static string Taipei_Standard_Time {
            get {
                return ResourceManager.GetString("Taipei Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Hobart.
        /// </summary>
        internal static string Tasmania_Standard_Time {
            get {
                return ResourceManager.GetString("Tasmania Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Araguaina.
        /// </summary>
        internal static string Tocantins_Standard_Time {
            get {
                return ResourceManager.GetString("Tocantins Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Osaka, Sapporo, Tokyo.
        /// </summary>
        internal static string Tokyo_Standard_Time {
            get {
                return ResourceManager.GetString("Tokyo Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Tomsk.
        /// </summary>
        internal static string Tomsk_Standard_Time {
            get {
                return ResourceManager.GetString("Tomsk Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+13:00) Nuku&apos;alofa.
        /// </summary>
        internal static string Tonga_Standard_Time {
            get {
                return ResourceManager.GetString("Tonga Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Chita.
        /// </summary>
        internal static string Transbaikal_Standard_Time {
            get {
                return ResourceManager.GetString("Transbaikal Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Istanbul.
        /// </summary>
        internal static string Turkey_Standard_Time {
            get {
                return ResourceManager.GetString("Turkey Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Turks and Caicos.
        /// </summary>
        internal static string Turks_And_Caicos_Standard_Time {
            get {
                return ResourceManager.GetString("Turks And Caicos Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Ulaanbaatar.
        /// </summary>
        internal static string Ulaanbaatar_Standard_Time {
            get {
                return ResourceManager.GetString("Ulaanbaatar Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Indiana (East).
        /// </summary>
        internal static string US_Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("US Eastern Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Arizona.
        /// </summary>
        internal static string US_Mountain_Standard_Time {
            get {
                return ResourceManager.GetString("US Mountain Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC) Coordinated Universal Time.
        /// </summary>
        internal static string UTC {
            get {
                return ResourceManager.GetString("UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-02:00) Coordinated Universal Time-02.
        /// </summary>
        internal static string UTC_02 {
            get {
                return ResourceManager.GetString("UTC-02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-08:00) Coordinated Universal Time-08.
        /// </summary>
        internal static string UTC_08 {
            get {
                return ResourceManager.GetString("UTC-08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-09:00) Coordinated Universal Time-09.
        /// </summary>
        internal static string UTC_09 {
            get {
                return ResourceManager.GetString("UTC-09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-11:00) Coordinated Universal Time-11.
        /// </summary>
        internal static string UTC_11 {
            get {
                return ResourceManager.GetString("UTC-11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Coordinated Universal Time+12.
        /// </summary>
        internal static string UTC_12 {
            get {
                return ResourceManager.GetString("UTC+12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+13:00) Coordinated Universal Time+13.
        /// </summary>
        internal static string UTC_13 {
            get {
                return ResourceManager.GetString("UTC+13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Caracas.
        /// </summary>
        internal static string Venezuela_Standard_Time {
            get {
                return ResourceManager.GetString("Venezuela Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Vladivostok.
        /// </summary>
        internal static string Vladivostok_Standard_Time {
            get {
                return ResourceManager.GetString("Vladivostok Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Volgograd.
        /// </summary>
        internal static string Volgograd_Standard_Time {
            get {
                return ResourceManager.GetString("Volgograd Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Perth.
        /// </summary>
        internal static string W__Australia_Standard_Time {
            get {
                return ResourceManager.GetString("W. Australia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) West Central Africa.
        /// </summary>
        internal static string W__Central_Africa_Standard_Time {
            get {
                return ResourceManager.GetString("W. Central Africa Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna.
        /// </summary>
        internal static string W__Europe_Standard_Time {
            get {
                return ResourceManager.GetString("W. Europe Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Hovd.
        /// </summary>
        internal static string W__Mongolia_Standard_Time {
            get {
                return ResourceManager.GetString("W. Mongolia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Ashgabat, Tashkent.
        /// </summary>
        internal static string West_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("West Asia Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Gaza, Hebron.
        /// </summary>
        internal static string West_Bank_Standard_Time {
            get {
                return ResourceManager.GetString("West Bank Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Guam, Port Moresby.
        /// </summary>
        internal static string West_Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("West Pacific Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Yakutsk.
        /// </summary>
        internal static string Yakutsk_Standard_Time {
            get {
                return ResourceManager.GetString("Yakutsk Standard Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Yukon.
        /// </summary>
        internal static string Yukon_Standard_Time {
            get {
                return ResourceManager.GetString("Yukon Standard Time", resourceCulture);
            }
        }
    }
}
