using Indice.Features.Messages.Core.Data;
using Indice.Features.Messages.Core.Data.Models;
using Indice.Features.Messages.Core.Models;
using Indice.Features.Messages.Core.Services.Abstractions;
using Indice.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace Indice.Features.Messages.Core.Services;

/// <inheritdoc/>
public class DatabaseCleanUpService : IDatabaseCleanUpService
{
    private readonly DatabaseCleanUpOptions _options;
    private CampaignsDbContext DbContext { get; }
    private readonly IFileService FileService;

    /// <summary>
    /// Constructs the service.
    /// </summary>
    /// <param name="options">Retention policies for database cleanup.</param>
    /// <param name="dbContext">Database context for accessing campaign data.</param>
    public DatabaseCleanUpService(IOptions<DatabaseCleanUpOptions> options, CampaignsDbContext dbContext, IFileServiceFactory fileServiceFactory) {
        _options = options.Value;
        DbContext = dbContext;
        //FileService = fileServiceFactory.Create(KeyedServiceNames.FileServiceKey) ?? throw new ArgumentNullException(nameof(fileServiceFactory), $"Service {KeyedServiceNames.FileServiceKey} was not registered");
    }

    /// <summary>
    /// Cleans up campaigns with an inbox and their related Data.
    /// </summary>
    /// <returns></returns>
    public async Task CleanUpCampaignsWithInboxAsync() {
        await CleanUpDataAsync(true);
    }

    /// <summary>
    /// Cleans up campaigns without an inbox and their related Data.
    /// </summary>
    /// <returns></returns>
    public async Task CleanUpCampaignsWithoutInboxAsync() {
        await CleanUpDataAsync(false);
    }

    private async Task CleanUpDataAsync(bool hasInbox) {
        bool hasMoreRecords = true;
        while (hasMoreRecords) {
            var cutOffDate = DateTimeOffset.UtcNow.AddDays(-_options.CampaignsWithoutInboxRetentionPeriodInDays);
            //has Inbox
            var query = DbContext.Campaigns.AsNoTracking().Where(x => hasInbox ? x.MessageChannelKind.HasFlag(MessageChannelKind.Inbox) : !x.MessageChannelKind.HasFlag(MessageChannelKind.Inbox));
            query = query.Where(x => x.CreatedAt <= cutOffDate && x.Published &&
            (!(x.ActivePeriod != null && x.ActivePeriod.From != null) || x.ActivePeriod.From <= cutOffDate)).OrderBy(x => x.CreatedAt).Take(_options.DeletionBatchSize);

            //unfortunately - I think that I have to materialize this
            var deletionCampaignData = await query.Select(x => new DbCampaign { Id = x.Id, AttachmentId = x.AttachmentId, DistributionListId = x.DistributionListId!.Value }).ToListAsync();

            if (deletionCampaignData.Count == 0) {
                break;
            }
            using (var transaction = await DbContext.Database.BeginTransactionAsync()) {
                try {
                    //Delete the campaigns and messages
                    await DbContext.Campaigns.Where(x => deletionCampaignData.Select(c => c.Id).Contains(x.Id)).ExecuteDeleteAsync();
                    //Delete the autogenerated distribution lists
                    await DbContext.DistributionLists.Where(x => x.CreatedBy!.ToLower().Trim() == "system" && deletionCampaignData.Select(c => c.DistributionListId).Contains(x.Id)).ExecuteDeleteAsync();
                    await DbContext.MessageEvents.Where(x => deletionCampaignData.Select(c => c.Id).Contains(x.CampaignId)).ExecuteDeleteAsync();
                    await transaction.CommitAsync();
                } catch (Exception ex) {
                    await transaction.RollbackAsync();
                    throw;
                }
            }
            var attachmentIds = deletionCampaignData.Select(x => x.AttachmentId);
            await DeleteAttachments(attachmentIds);
            break;
        }
    }

    private async Task DeleteAttachments(IEnumerable<Guid?> attachmentIds) {
        // bring the attatchments? -> should I bring them from the start?
        var dbAttachments = await DbContext.Attachments.Where(x => attachmentIds.Contains(x.Id)).ToListAsync();
        if (dbAttachments.Any()) {
            //here I will call the delete of the file service - so that I can delete the files from blob storage as well
            foreach (var dbAttachment in dbAttachments) {
                var path = $"campaigns/{dbAttachment.Guid.ToString("N")[..2]}/{dbAttachment.Guid:N}.{dbAttachment.FileExtension?.TrimStart('.')}";
                try {
                    await FileService.DeleteAsync(path);
                } catch {
                    // catching any exception here to avoid breaking the cleanup process due to file deletion issues
                }
            }
            await DbContext.Attachments.Where(x => attachmentIds.Contains(x.Id)).ExecuteDeleteAsync();
        }
    }
}
