using Indice.Features.Messages.Core.Data;
using Indice.Features.Messages.Core.Data.Models;
using Indice.Features.Messages.Core.Models;
using Indice.Features.Messages.Core.Services.Abstractions;
using Indice.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace Indice.Features.Messages.Core.Services;

/// <inheritdoc/>
public class DatabaseCleanUpService : IDatabaseCleanUpService
{
    private readonly DatabaseCleanUpOptions _options;
    private CampaignsDbContext DbContext { get; }
    private readonly IFileService FileService;

    /// <summary>
    /// Constructs the service.
    /// </summary>
    /// <param name="options">Retention policies for database cleanup.</param>
    /// <param name="dbContext">Database context for accessing campaign data.</param>
    public DatabaseCleanUpService(IOptions<DatabaseCleanUpOptions> options, CampaignsDbContext dbContext, IFileServiceFactory fileServiceFactory) {
        _options = options.Value;
        DbContext = dbContext;
        FileService = fileServiceFactory.Create(KeyedServiceNames.FileServiceKey) ?? throw new ArgumentNullException(nameof(fileServiceFactory), $"Service {KeyedServiceNames.FileServiceKey} was not registered");
    }

    /// <summary>
    /// Cleans up campaigns with an inbox and their related Data.
    /// </summary>
    /// <returns></returns>
    public async Task CleanUpCampaignsWithInboxAsync() {
        if(!_options.Enabled) {
            return;
        }
        var cutOffDate =  DateTimeOffset.UtcNow.AddDays(-_options.RetentionDaysForInbox);
        var query = DbContext.Campaigns.AsNoTracking().Where(x =>  x.MessageChannelKind.HasFlag(MessageChannelKind.Inbox));
        await CleanUpDataAsync(query, cutOffDate);
    }

    /// <summary>
    /// Cleans up campaigns without an inbox and their related Data.
    /// </summary>
    /// <returns></returns>
    public async Task CleanUpCampaignsWithoutInboxAsync() {
        if (!_options.Enabled) {
            return;
        }
        var cutOffDate = DateTimeOffset.UtcNow.AddDays(-_options.RetentionDaysForOther);
        var query = DbContext.Campaigns.AsNoTracking().Where(x => !x.MessageChannelKind.HasFlag(MessageChannelKind.Inbox));
        await CleanUpDataAsync(query, cutOffDate);
    }

    private async Task CleanUpDataAsync(IQueryable<DbCampaign> query, DateTimeOffset cutOffDate) {
        bool hasMoreRecords = true;
        while (hasMoreRecords) {
            // old and published
            query = query.Where(x => x.CreatedAt <= cutOffDate && x.Published &&
            (!(x.ActivePeriod != null && x.ActivePeriod.From != null) || x.ActivePeriod.From <= cutOffDate))
                .OrderBy(x => x.CreatedAt)
                .Take(_options.DeletionBatchSize);
            var deletionCampaignData = await query.Select(x => new DbCampaign { Id = x.Id, AttachmentId = x.AttachmentId, DistributionListId = x.DistributionListId!.Value }).ToListAsync();
            //nothing left to delete...
            if (deletionCampaignData.Count == 0) {
                break;
            }
            await DeleteCampaignBatchAsync(deletionCampaignData);
        }
    }

    /// <summary>
    /// Deletes a batch of campaigns along with their related data within a transaction.
    /// </summary>
    /// <param name="deletionCampaignData"></param>
    /// <returns></returns>
    private async Task DeleteCampaignBatchAsync(List<DbCampaign> deletionCampaignData) {
        using (var transaction = await DbContext.Database.BeginTransactionAsync()) {
            try {
                //Delete the campaigns and messages
                await DbContext.Campaigns.Where(x => deletionCampaignData.Select(c => c.Id).Contains(x.Id)).ExecuteDeleteAsync();
                //Delete the autogenerated distribution lists
                await DbContext.DistributionLists.Where(x => x.CreatedBy!.ToLower().Trim() == "system" && deletionCampaignData.Select(c => c.DistributionListId).Contains(x.Id)).ExecuteDeleteAsync();
                await DbContext.MessageEvents.Where(x => deletionCampaignData.Select(c => c.Id).Contains(x.CampaignId)).ExecuteDeleteAsync();
                await transaction.CommitAsync();
            } catch (Exception) {
                await transaction.RollbackAsync();
                throw;
            }
        }
        var attachmentIds = deletionCampaignData.Select(x => x.AttachmentId);
        await DeleteAttachments(attachmentIds);
    }

    /// <summary>
    /// Deletes attachments both from the file storage and the database.
    /// </summary>
    /// <param name="attachmentIds"></param>
    /// <returns></returns>
    private async Task DeleteAttachments(IEnumerable<Guid?> attachmentIds) {
        var dbAttachments = await DbContext.Attachments.Where(x => attachmentIds.Contains(x.Id)).ToListAsync();
        if (dbAttachments.Any()) {
            foreach (var dbAttachment in dbAttachments) {
                // the path where the data is stored - this could become a configuration option if needed
                var path = $"campaigns/{dbAttachment.Guid.ToString("N")[..2]}/{dbAttachment.Guid:N}.{dbAttachment.FileExtension?.TrimStart('.')}";
                try {
                    await FileService.DeleteAsync(path);
                } 
                catch {
                    // catching any exception here to avoid breaking the cleanup process due to file deletion issues
                }
            }
            await DbContext.Attachments.Where(x => attachmentIds.Contains(x.Id)).ExecuteDeleteAsync();
        }
    }
}
