using System.ComponentModel.DataAnnotations;

namespace Indice.Features.Identity.Server.Manager.Models;

/// <summary>Models a password change request by the user.</summary>
public class ChangePasswordRequest
{
    /// <summary>The current password of the user.</summary>
    [Required(ErrorMessage = "Field 'OldPassword' is required.")]
    public string OldPassword { get; set; }
    /// <summary>The new password of the user.</summary>
    [Required(ErrorMessage = "Field 'NewPassword' is required.")]
    public string NewPassword { get; set; }
    /// <summary>The new password confirmation.</summary>
    [Compare("NewPassword", ErrorMessage = "Password confirmation is not correct.")]
    public string NewPasswordConfirmation { get; set; }
}

/// <summary>Models a request to set a user's password.</summary>
public class SetPasswordRequest
{
    /// <summary>The password of the user.</summary>
    [Required(ErrorMessage = "Field 'Password' is required.")]
    public string Password { get; set; }
    /// <summary>Forces the user to change his password after changed by the system admin.</summary>
    public bool? ChangePasswordAfterFirstSignIn { get; set; }
    /// <summary>Bypasses all password validation rules.</summary>
    public bool? BypassPasswordValidation { get; set; }
}

/// <summary>Triggers the initiation for a password reset.</summary>
public class ForgotPasswordRequest
{
    /// <summary>The user's email.</summary>
    public string Email { get; set; }
    /// <summary>The url to return to.</summary>
    public string ReturnUrl { get; set; }
}

/// <summary>The model containing a verification token generated by the system.</summary>
public class VerifyTokenModel
{
    /// <summary>The token.</summary>
    public string Token { get; set; }
}

/// <summary>
/// Completes the password reset process.
/// Maybe we need to retire one of them. They only differ by their use of the Email or username fields for user retrieval.
/// </summary>
public class ForgotPasswordConfirmationRequest : VerifyTokenModel
{
    /// <summary>The user's email.</summary>
    public string Email { get; set; }
    /// <summary>The new password.</summary>
    public string NewPassword { get; set; }
    /// <summary>The new password confirmed (optional).</summary>
    public string NewPasswordConfirmation { get; set; }
    /// <summary>The url to return to.</summary>
    public string ReturnUrl { get; set; }
}
