name: Build and test steps
description: Composite action for executing dotnet build + test

runs:
  using: 'composite'
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
      with:
        egress-policy: audit

    - name: Setup .NET
      uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852 # v4.2.0
      with:
        dotnet-version: 8.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${HELLO_WORLD_SECRET}

    - name: Use Node.js 20.x
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 20
 
    - name: NPM Install and Build Identity UI
      shell: pwsh
      run: |
        cd src/Indice.Features.Identity.UI
        npm install --force
        npm run gulp -- copy:libs
        npm run gulp -- sass

    - name: NPM Install Cases
      shell: pwsh
      run: |
        cd src/Indice.Features.Cases.App
        npm install

    - name: NPM Install AdminUI
      shell: pwsh
      run: |
        cd src/Indice.Features.Identity.AdminUI.App
        npm install

    - name: NPM Install Messages
      shell: pwsh
      run: |
        cd src/Indice.Features.Messages.App
        npm install

    - name: NPM Install Risk
      shell: pwsh
      run: |
        cd src/Indice.Features.Risk.App
        npm install

    - name: Create .nuget dir
      shell: pwsh
      run: |
        if (!(Test-Path -Path ".\.nuget" ))
        {
          New-Item -ItemType "directory" -Path ".\.nuget"
        }
        if (!(Test-Path -Path ".\.nuget\packages" ))
        {
          New-Item -ItemType "directory" -Path ".\.nuget\packages"
        }
      
    - name: Dotnet restore
      shell: pwsh
      run: dotnet restore /nowarn:netsdk1138

    - name: Dotnet build SPAs
      shell: pwsh
      run: dotnet build Indice.Platform.Ecmascript.slnf --no-restore --configuration Release

    - name: Dotnet build
      shell: pwsh
      run: dotnet build Indice.Platform.slnf --no-restore --configuration Release
      
    - name: Test with dotnet
      shell: pwsh
      run: dotnet test --no-build --configuration Release --logger trx --results-directory "TestResults"
    
    - name: Test Reporter
      uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
      if: always()
      with:
        name: DotNET Tests
        path: "TestResults/*.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
