<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFrameworks></TargetFrameworks>
    <TargetFramework>net10.0</TargetFramework>    
    <VersionPrefix>$(VersionPrefixAgents)</VersionPrefix>
    <VersionSuffix>beta12</VersionSuffix>
    
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <SpaProjectName>browser</SpaProjectName>
    <SpaSourceFolder>..\Indice.Features.Agents.App</SpaSourceFolder>
    <SpaDistFolder>$(SpaSourceFolder)\dist\dex-app</SpaDistFolder>
    <PackageReleaseNotes></PackageReleaseNotes>
    <PackageTags>AspNetCore;Agents;AI Foundation</PackageTags>
  </PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="$(SpaDistFolder)\**\*" Exclude="$(SpaDistFolder)\**\index.html;$(SpaDistFolder)\**\3rdpartylicenses.txt;$(SpaDistFolder)\**\prerendered-routes.json" />
		<EmbeddedResource Include="$(SpaProjectName)\index.html" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Indice.AspNetCore.EmbeddedUI" Version="$(VersionPrefixCore)-*" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Indice.AspNetCore.EmbeddedUI\Indice.AspNetCore.EmbeddedUI.csproj" />
		<ProjectReference Include="..\Indice.Features.Agents.App\Indice.Features.Agents.App.esproj" Condition="'$(Configuration)' == 'Debug'">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>
</Project>
