//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indice.Features.Identity.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indice.Features.Identity.UI.IdentityLabels", typeof(IdentityLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptTerms_Accept {
            get {
                return ResourceManager.GetString("AcceptTerms_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; conditions acceptance.
        /// </summary>
        public static string AcceptTerms_AcceptTermsAndConditions {
            get {
                return ResourceManager.GetString("AcceptTerms_AcceptTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read and accept the terms and conditions to continue..
        /// </summary>
        public static string AcceptTerms_ReadAndAcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms_ReadAndAcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string AcceptTerms_Reject {
            get {
                return ResourceManager.GetString("AcceptTerms_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string AddEmail_Next {
            get {
                return ResourceManager.GetString("AddEmail_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AddEmail_Save {
            get {
                return ResourceManager.GetString("AddEmail_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify email.
        /// </summary>
        public static string AddEmail_Verify_email {
            get {
                return ResourceManager.GetString("AddEmail_Verify email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddPassword_Add {
            get {
                return ResourceManager.GetString("AddPassword_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Password.
        /// </summary>
        public static string AddPassword_AddPassword {
            get {
                return ResourceManager.GetString("AddPassword_AddPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string AddPassword_Newpassword {
            get {
                return ResourceManager.GetString("AddPassword_Newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string AddPassword_PasswordConfirmation {
            get {
                return ResourceManager.GetString("AddPassword_PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully added.
        /// </summary>
        public static string AddPassword_PasswordSuccessfullyAdded {
            get {
                return ResourceManager.GetString("AddPassword_PasswordSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed..
        /// </summary>
        public static string AddPassword_ProcessCompleted {
            get {
                return ResourceManager.GetString("AddPassword_ProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required.
        /// </summary>
        public static string AddPassword_Required {
            get {
                return ResourceManager.GetString("AddPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add phone.
        /// </summary>
        public static string AddPhone_AddPhone {
            get {
                return ResourceManager.GetString("AddPhone_AddPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add phone number.
        /// </summary>
        public static string AddPhone_AddPhoneNumber {
            get {
                return ResourceManager.GetString("AddPhone_AddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Code.
        /// </summary>
        public static string AddPhone_CallingCode {
            get {
                return ResourceManager.GetString("AddPhone_CallingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string AddPhone_PhoneNumber {
            get {
                return ResourceManager.GetString("AddPhone_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AddPhone_Save {
            get {
                return ResourceManager.GetString("AddPhone_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting....
        /// </summary>
        public static string Challenge_Redirecting {
            get {
                return ResourceManager.GetString("Challenge_Redirecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangePassword_Change {
            get {
                return ResourceManager.GetString("ChangePassword_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword_ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ChangePassword_NewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string ChangePassword_OldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed.
        /// </summary>
        public static string ChangePassword_PasswordSuccessfullyChanged {
            get {
                return ResourceManager.GetString("ChangePassword_PasswordSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed..
        /// </summary>
        public static string ChangePassword_ProcessCompleted {
            get {
                return ResourceManager.GetString("ChangePassword_ProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with a different account.
        /// </summary>
        public static string ChangePassword_SignWithDifferentAccount {
            get {
                return ResourceManager.GetString("ChangePassword_SignWithDifferentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is already verified. Thank you.
        /// </summary>
        public static string ConfirmEmail_AlreadyVerified {
            get {
                return ResourceManager.GetString("ConfirmEmail_AlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string ConfirmEmail_Click {
            get {
                return ResourceManager.GetString("ConfirmEmail_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take a moment. Click on the link below to verify your email address..
        /// </summary>
        public static string ConfirmEmail_ClickToVerify {
            get {
                return ResourceManager.GetString("ConfirmEmail_ClickToVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now close this browse window..
        /// </summary>
        public static string ConfirmEmail_Closewindow {
            get {
                return ResourceManager.GetString("ConfirmEmail_Closewindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been successfully confirmed..
        /// </summary>
        public static string ConfirmEmail_Confrimation {
            get {
                return ResourceManager.GetString("ConfirmEmail_Confrimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not reply, as this address does not receive email messages and you will not receive a response..
        /// </summary>
        public static string ConfirmEmail_DoNotReply {
            get {
                return ResourceManager.GetString("ConfirmEmail_DoNotReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation.
        /// </summary>
        public static string ConfirmEmail_EmailConfirmation {
            get {
                return ResourceManager.GetString("ConfirmEmail_EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to sign in or go back..
        /// </summary>
        public static string ConfirmEmail_GoBackToSignIn {
            get {
                return ResourceManager.GetString("ConfirmEmail_GoBackToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string ConfirmEmail_here {
            get {
                return ResourceManager.GetString("ConfirmEmail_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification link has expired..
        /// </summary>
        public static string ConfirmEmail_LinkExpired {
            get {
                return ResourceManager.GetString("ConfirmEmail_LinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in and resend the link.
        /// </summary>
        public static string ConfirmEmail_LoginResendText {
            get {
                return ResourceManager.GetString("ConfirmEmail_LoginResendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you feel you got this error by mistake, simply click.
        /// </summary>
        public static string ConfirmEmail_MistakeText {
            get {
                return ResourceManager.GetString("ConfirmEmail_MistakeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action was taken..
        /// </summary>
        public static string ConfirmEmail_NoActionTaken {
            get {
                return ResourceManager.GetString("ConfirmEmail_NoActionTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service email contains information related to your account..
        /// </summary>
        public static string ConfirmEmail_ServiceEmailInfo {
            get {
                return ResourceManager.GetString("ConfirmEmail_ServiceEmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string ConfirmEmail_Verify {
            get {
                return ResourceManager.GetString("ConfirmEmail_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying your email..
        /// </summary>
        public static string ConfirmEmail_VerifyingEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail_VerifyingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string ConfirmEmailChange_Click {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now close this browse window..
        /// </summary>
        public static string ConfirmEmailChange_CloseWindowMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_CloseWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Change Confirmation.
        /// </summary>
        public static string ConfirmEmailChange_Confirmation {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been successfully changed..
        /// </summary>
        public static string ConfirmEmailChange_ConfirmationEmailChanged {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_ConfirmationEmailChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is already verified. Thank you.
        /// </summary>
        public static string ConfirmEmailChange_ConfirmationVerified {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_ConfirmationVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string ConfirmEmailChange_here {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification link has expired..
        /// </summary>
        public static string ConfirmEmailChange_LinkExpired {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_LinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in and resend the link.
        /// </summary>
        public static string ConfirmEmailChange_LoginResendText {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_LoginResendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you feel you got this error by mistake, simply click.
        /// </summary>
        public static string ConfirmEmailChange_MistakeText {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_MistakeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action was taken..
        /// </summary>
        public static string ConfirmEmailChange_NoAction {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to sign in or go back..
        /// </summary>
        public static string ConfirmEmailChange_SignInGoBack {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_SignInGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take a moment. Click on the link below to verify your email address..
        /// </summary>
        public static string ConfirmEmailChange_VerificationText {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_VerificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string ConfirmEmailChange_Verify {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying your email..
        /// </summary>
        public static string ConfirmEmailChange_VerifyingEmail {
            get {
                return ResourceManager.GetString("ConfirmEmailChange_VerifyingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Consent_Accept {
            get {
                return ResourceManager.GetString("Consent_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.
        /// </summary>
        public static string Consent_app {
            get {
                return ResourceManager.GetString("Consent_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Access.
        /// </summary>
        public static string Consent_Application_Access {
            get {
                return ResourceManager.GetString("Consent_Application Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Consent_Cancel {
            get {
                return ResourceManager.GetString("Consent_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string Consent_code {
            get {
                return ResourceManager.GetString("Consent_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent.
        /// </summary>
        public static string Consent_Consent {
            get {
                return ResourceManager.GetString("Consent_Consent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string Consent_Personal_Information {
            get {
                return ResourceManager.GetString("Consent_Personal Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember My Decision.
        /// </summary>
        public static string Consent_Remember_My_Decision {
            get {
                return ResourceManager.GetString("Consent_Remember My Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code.
        /// </summary>
        public static string Consent_Security_code {
            get {
                return ResourceManager.GetString("Consent_Security code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string Consent_send {
            get {
                return ResourceManager.GetString("Consent_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This.
        /// </summary>
        public static string Consent_This {
            get {
                return ResourceManager.GetString("Consent_This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app would like to.
        /// </summary>
        public static string Consent_This_app_would_like_to {
            get {
                return ResourceManager.GetString("Consent_This app would like to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to your phone.
        /// </summary>
        public static string Consent_to_your_phone {
            get {
                return ResourceManager.GetString("Consent_to your phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck the permissions you do not wish to grant..
        /// </summary>
        public static string Consent_Uncheck_the_permissions_you_do_not_wish_to_grant_ {
            get {
                return ResourceManager.GetString("Consent_Uncheck the permissions you do not wish to grant.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to would like to.
        /// </summary>
        public static string Consent_would_like_to {
            get {
                return ResourceManager.GetString("Consent_would like to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Email_Body_Hi {
            get {
                return ResourceManager.GetString("Email_Body_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Email_Body_Organization {
            get {
                return ResourceManager.GetString("Email_Body_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely.
        /// </summary>
        public static string Email_Body_Sincerely {
            get {
                return ResourceManager.GetString("Email_Body_Sincerely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string Email_Body_Thanks {
            get {
                return ResourceManager.GetString("Email_Body_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Email_Preheader_Here {
            get {
                return ResourceManager.GetString("Email_Preheader_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to get verified.
        /// </summary>
        public static string Email_Preheader_ToGetVerified {
            get {
                return ResourceManager.GetString("Email_Preheader_ToGetVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need you to verify your email. Please click.
        /// </summary>
        public static string Email_Preheader_Verify {
            get {
                return ResourceManager.GetString("Email_Preheader_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Email_Reset_Password {
            get {
                return ResourceManager.GetString("Email_Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not request your password to be reset you may safely ignore this message..
        /// </summary>
        public static string Email_ResetPassword_IgnoreNotice {
            get {
                return ResourceManager.GetString("Email_ResetPassword_IgnoreNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received a request to reset your password. If you asked to reset your password, please click the following link:.
        /// </summary>
        public static string Email_ResetPassword_RequestInfo {
            get {
                return ResourceManager.GetString("Email_ResetPassword_RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete your registration, please confirm your email address by clicking.
        /// </summary>
        public static string EmailRegister_Body_ConfirmEmail {
            get {
                return ResourceManager.GetString("EmailRegister_Body_ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string EmailRegister_Body_Hi {
            get {
                return ResourceManager.GetString("EmailRegister_Body_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not create an account, you can safely ignore this email..
        /// </summary>
        public static string EmailRegister_Body_IgnoreNotice {
            get {
                return ResourceManager.GetString("EmailRegister_Body_IgnoreNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for joining!.
        /// </summary>
        public static string EmailRegister_Body_Thanks {
            get {
                return ResourceManager.GetString("EmailRegister_Body_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}! We’re excited to have you on board..
        /// </summary>
        public static string EmailRegister_Body_Welcome {
            get {
                return ResourceManager.GetString("EmailRegister_Body_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}! Please confirm your email to get started..
        /// </summary>
        public static string EmailRegister_Subject {
            get {
                return ResourceManager.GetString("EmailRegister_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string EmailSecurity_Body_Client {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not perform this action, please contact support immediately..
        /// </summary>
        public static string EmailSecurity_Body_ContactSupport {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string EmailSecurity_Body_Device {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailSecurity_Body_Email {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event details:.
        /// </summary>
        public static string EmailSecurity_Body_EventDetails {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We wanted to let you know that a security-related event occurred on your account..
        /// </summary>
        public static string EmailSecurity_Body_EventOccurred {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_EventOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time.
        /// </summary>
        public static string EmailSecurity_Body_EventTime {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string EmailSecurity_Body_Hi {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string EmailSecurity_Body_Location {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (It may not match the exact location).
        /// </summary>
        public static string EmailSecurity_Body_LocationNotice {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_LocationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string EmailSecurity_Body_Username {
            get {
                return ResourceManager.GetString("EmailSecurity_Body_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security notification regarding your account..
        /// </summary>
        public static string EmailSecurity_Preheader {
            get {
                return ResourceManager.GetString("EmailSecurity_Preheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Notification.
        /// </summary>
        public static string EmailSecurity_Subject {
            get {
                return ResourceManager.GetString("EmailSecurity_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Error {
            get {
                return ResourceManager.GetString("Error_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back home.
        /// </summary>
        public static string Error_Go_back_home {
            get {
                return ResourceManager.GetString("Error_Go_back_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Seems we encountered an error..
        /// </summary>
        public static string Error_Oops__Seems_we_encountered_an_error_ {
            get {
                return ResourceManager.GetString("Error_Oops! Seems we encountered an error.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Id.
        /// </summary>
        public static string Error_Request_Id {
            get {
                return ResourceManager.GetString("Error_Request Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Footer_Contact_us {
            get {
                return ResourceManager.GetString("Footer_Contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery.
        /// </summary>
        public static string Footer_Discovery {
            get {
                return ResourceManager.GetString("Footer_Discovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Footer_Privacy {
            get {
                return ResourceManager.GetString("Footer_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Footer_Terms {
            get {
                return ResourceManager.GetString("Footer_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPassword_Forgot_password {
            get {
                return ResourceManager.GetString("ForgotPassword_Forgot password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sent.
        /// </summary>
        public static string ForgotPassword_Request_sent {
            get {
                return ResourceManager.GetString("ForgotPassword_Request sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string ForgotPassword_Resend {
            get {
                return ResourceManager.GetString("ForgotPassword_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ForgotPassword_Send {
            get {
                return ResourceManager.GetString("ForgotPassword_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To have your password reset, enter your username or email address below. We will then send an email containing a link to reset your password..
        /// </summary>
        public static string ForgotPassword_To_have_your_password_reset__enter_your_username_or_email_address_below__We_will_then_send_an_email_containing_a_link_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("ForgotPassword_To have your password reset, enter your username or email address " +
                        "below. We will then send an email containing a link to reset your password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string ForgotPassword_Username {
            get {
                return ResourceManager.GetString("ForgotPassword_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation_Forgot_Password_Confirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Forgot Password Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ForgotPasswordConfirmation_New_Password {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string ForgotPasswordConfirmation_Password_changed {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Password changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your new password.
        /// </summary>
        public static string ForgotPasswordConfirmation_Please_fill_in_your_new_password {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Please fill in your new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ForgotPasswordConfirmation_Send {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is the list of applications you have given access to and the names of the resources they have access to..
        /// </summary>
        public static string Grants_Below_is_the_list_of_applications_you_have_given_access_to_and_the_names_of_the_resources_they_have_access_to_ {
            get {
                return ResourceManager.GetString("Grants_Below is the list of applications you have given access to and the names o" +
                        "f the resources they have access to.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client logo.
        /// </summary>
        public static string Grants_Client_logo {
            get {
                return ResourceManager.GetString("Grants_Client logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string Grants_Created_ {
            get {
                return ResourceManager.GetString("Grants_Created:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires on.
        /// </summary>
        public static string Grants_Expires_on {
            get {
                return ResourceManager.GetString("Grants_Expires on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants.
        /// </summary>
        public static string Grants_Grants {
            get {
                return ResourceManager.GetString("Grants_Grants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke Access.
        /// </summary>
        public static string Grants_Revoke_Access {
            get {
                return ResourceManager.GetString("Grants_Revoke Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not provided access to any applications.
        /// </summary>
        public static string Grants_You_have_not_provided_access_to_any_applications {
            get {
                return ResourceManager.GetString("Grants_You have not provided access to any applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Welcome&lt;/strong&gt;&lt;br&gt; to our Digital Services Portal of {0}.
        /// </summary>
        public static string Home__strong_Welcome__strong__br__to_our_Digital_Services_Portal_of__0_ {
            get {
                return ResourceManager.GetString("Home_<strong>Welcome</strong><br> to our Digital Services Portal of {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorized applications.
        /// </summary>
        public static string Home_authorized_applications {
            get {
                return ResourceManager.GetString("Home_authorized applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check and revoke your.
        /// </summary>
        public static string Home_Check_and_revoke_your {
            get {
                return ResourceManager.GetString("Home_Check and revoke your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Services.
        /// </summary>
        public static string Home_Digital_Services {
            get {
                return ResourceManager.GetString("Home_Digital Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Home_here {
            get {
                return ResourceManager.GetString("Home_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your grants.
        /// </summary>
        public static string Home_Manage_your_grants {
            get {
                return ResourceManager.GetString("Home_Manage your grants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to the application.
        /// </summary>
        public static string Home_Please_login_to_the_application {
            get {
                return ResourceManager.GetString("Home_Please login to the application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        public static string Home_Portal {
            get {
                return ResourceManager.GetString("Home_Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Identity portal gives you access to all {0} services with one account. A place to manage your user profile and account access settings. Use the links below to get started..
        /// </summary>
        public static string Home_The_Identity_portal_gives_you_access_to_all__0__services_with_one_account__A_place_to_manage_your_user_profile_and_account_access_settings__Use_the_links_below_to_get_started_ {
            get {
                return ResourceManager.GetString("Home_The Identity portal gives you access to all {0} services with one account. A" +
                        " place to manage your user profile and account access settings. Use the links be" +
                        "low to get started.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        public static string Home_Welcome_back {
            get {
                return ResourceManager.GetString("Home_Welcome back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {0} Digital Services &lt;strong&gt;Portal&lt;/strong&gt;.
        /// </summary>
        public static string Home_Welcome_to_the__0__Digital_Services__strong_Portal__strong_ {
            get {
                return ResourceManager.GetString("Home_Welcome to the {0} Digital Services <strong>Portal</strong>", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string LoggedOut_Click {
            get {
                return ResourceManager.GetString("LoggedOut_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string LoggedOut_here {
            get {
                return ResourceManager.GetString("LoggedOut_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LoggedOut_Logout {
            get {
                return ResourceManager.GetString("LoggedOut_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to return to the application.
        /// </summary>
        public static string LoggedOut_to_return_to_the_application {
            get {
                return ResourceManager.GetString("LoggedOut_to return to the application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged out.
        /// </summary>
        public static string LoggedOut_You_are_now_logged_out {
            get {
                return ResourceManager.GetString("LoggedOut_You are now logged out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string Login_Don_t_have_an_account_ {
            get {
                return ResourceManager.GetString("Login_Don\'t have an account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Login_Forgot_password_ {
            get {
                return ResourceManager.GetString("Login_Forgot password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login request.
        /// </summary>
        public static string Login_Invalid_login_request {
            get {
                return ResourceManager.GetString("Login_Invalid login request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us.
        /// </summary>
        public static string Login_Join_us {
            get {
                return ResourceManager.GetString("Login_Join us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Login_OR {
            get {
                return ResourceManager.GetString("Login_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Login_Remember_me {
            get {
                return ResourceManager.GetString("Login_Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Login_Sign_in {
            get {
                return ResourceManager.GetString("Login_Sign in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no login schemes configured for this client..
        /// </summary>
        public static string Login_There_are_no_login_schemes_configured_for_this_client_ {
            get {
                return ResourceManager.GetString("Login_There are no login schemes configured for this client.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout_Logout {
            get {
                return ResourceManager.GetString("Logout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to logout?.
        /// </summary>
        public static string Logout_Would_you_like_to_logout_ {
            get {
                return ResourceManager.GetString("Logout_Would you like to logout?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Logout_Yes {
            get {
                return ResourceManager.GetString("Logout_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while sending the OTP code..
        /// </summary>
        public static string Mfa_An_unexpected_error_occurred_while_sending_the_OTP_code_ {
            get {
                return ResourceManager.GetString("Mfa_An unexpected error occurred while sending the OTP code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string Mfa_Authenticate {
            get {
                return ResourceManager.GetString("Mfa_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate yourself using:.
        /// </summary>
        public static string Mfa_Authenticate_yourself_using_ {
            get {
                return ResourceManager.GetString("Mfa_Authenticate yourself using:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Mfa_Back {
            get {
                return ResourceManager.GetString("Mfa_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because you&apos;ve turned on two-step verification, you need to approve request on your mobile app..
        /// </summary>
        public static string Mfa_Because_you_ve_turned_on_two_step_verification__you_need_to_approve_request_on_your_mobile_app_ {
            get {
                return ResourceManager.GetString("Mfa_Because you\'ve turned on two-step verification, you need to approve request o" +
                        "n your mobile app.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t use my app right now.
        /// </summary>
        public static string Mfa_I_can_t_use_my_app_right_now {
            get {
                return ResourceManager.GetString("Mfa_I can\'t use my app right now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t receive the notification/Resend..
        /// </summary>
        public static string Mfa_I_didn_t_receive_the_notification_Resend_ {
            get {
                return ResourceManager.GetString("Mfa_I didn\'t receive the notification/Resend.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I sign in frequently here. Remember this browser..
        /// </summary>
        public static string Mfa_I_sign_in_frequently_here__Remember_this_browser_ {
            get {
                return ResourceManager.GetString("Mfa_I sign in frequently here. Remember this browser.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Mfa_Login {
            get {
                return ResourceManager.GetString("Mfa_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multifactor Authentication.
        /// </summary>
        public static string Mfa_Multifactor_Authentication {
            get {
                return ResourceManager.GetString("Mfa_Multifactor Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other authentication methods....
        /// </summary>
        public static string Mfa_Other_authentication_methods___ {
            get {
                return ResourceManager.GetString("Mfa_Other authentication methods...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Code.
        /// </summary>
        public static string Mfa_OTP_Code {
            get {
                return ResourceManager.GetString("Mfa_OTP Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request denied.
        /// </summary>
        public static string Mfa_Request_denied {
            get {
                return ResourceManager.GetString("Mfa_Request denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string Mfa_Resend {
            get {
                return ResourceManager.GetString("Mfa_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send another request to my app.
        /// </summary>
        public static string Mfa_Send_another_request_to_my_app {
            get {
                return ResourceManager.GetString("Mfa_Send another request to my app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent an identity verification request to your mobile device, but you denied it..
        /// </summary>
        public static string Mfa_We_sent_an_identity_verification_request_to_your_mobile_device__but_you_denied_it_ {
            get {
                return ResourceManager.GetString("Mfa_We sent an identity verification request to your mobile device, but you denie" +
                        "d it.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We texted your phone {0}. Please enter the code to sign in..
        /// </summary>
        public static string Mfa_We_texted_your_phone__0___Please_enter_the_code_to_sign_in_ {
            get {
                return ResourceManager.GetString("Mfa_We texted your phone {0}. Please enter the code to sign in.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP login.
        /// </summary>
        public static string MfaModel_OTP_login {
            get {
                return ResourceManager.GetString("MfaModel_OTP login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP code is not valid..
        /// </summary>
        public static string MfaModel_The_OTP_code_is_not_valid_ {
            get {
                return ResourceManager.GetString("MfaModel_The OTP code is not valid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP code for login is: {0}.
        /// </summary>
        public static string MfaModel_Your_OTP_code_for_login_is___0_ {
            get {
                return ResourceManager.GetString("MfaModel_Your OTP code for login is: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable MFA.
        /// </summary>
        public static string MfaOnBoarding_Enable_MFA {
            get {
                return ResourceManager.GetString("MfaOnBoarding_Enable MFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your account safe.
        /// </summary>
        public static string MfaOnBoarding_Keep_your_account_safe {
            get {
                return ResourceManager.GetString("MfaOnBoarding_Keep your account safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string MfaOnBoarding_Next {
            get {
                return ResourceManager.GetString("MfaOnBoarding_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup an additional authentication method..
        /// </summary>
        public static string MfaOnBoarding_Setup_an_additional_authentication_method_ {
            get {
                return ResourceManager.GetString("MfaOnBoarding_Setup an additional authentication method.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA onboarding - SMS.
        /// </summary>
        public static string MfaOnBoardingAddPhone_MFA_onboarding___SMS {
            get {
                return ResourceManager.GetString("MfaOnBoardingAddPhone_MFA onboarding - SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string MfaOnBoardingAddPhone_Next {
            get {
                return ResourceManager.GetString("MfaOnBoardingAddPhone_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string MfaOnBoardingAddPhone_Phone_number {
            get {
                return ResourceManager.GetString("MfaOnBoardingAddPhone_Phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MfaOnBoardingAddPhone_Save {
            get {
                return ResourceManager.GetString("MfaOnBoardingAddPhone_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string MfaOnBoardingVerifyPhone_Code {
            get {
                return ResourceManager.GetString("MfaOnBoardingVerifyPhone_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string MfaOnBoardingVerifyPhone_Next {
            get {
                return ResourceManager.GetString("MfaOnBoardingVerifyPhone_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MfaOnBoardingVerifyPhone_Save {
            get {
                return ResourceManager.GetString("MfaOnBoardingVerifyPhone_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify phone number.
        /// </summary>
        public static string MfaOnBoardingVerifyPhone_Verify_phone_number {
            get {
                return ResourceManager.GetString("MfaOnBoardingVerifyPhone_Verify phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string PasswordExpired_Change_password {
            get {
                return ResourceManager.GetString("PasswordExpired_Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string PasswordExpired_New_password {
            get {
                return ResourceManager.GetString("PasswordExpired_New password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PasswordExpired_Next {
            get {
                return ResourceManager.GetString("PasswordExpired_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PasswordExpired_Save {
            get {
                return ResourceManager.GetString("PasswordExpired_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?ew password confirmation.
        /// </summary>
        public static string PasswordExpired_Νew_password_confirmation {
            get {
                return ResourceManager.GetString("PasswordExpired_Νew password confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmation email has been sent to {0}..
        /// </summary>
        public static string Profile_A_confirmation_email_has_been_sent_to__0__ {
            get {
                return ResourceManager.GetString("Profile_A confirmation email has been sent to {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to your new email address in order to confirm it..
        /// </summary>
        public static string Profile_An_email_has_been_sent_to_your_new_email_address_in_order_to_confirm_it_ {
            get {
                return ResourceManager.GetString("Profile_An email has been sent to your new email address in order to confirm it.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string Profile_Birth_date {
            get {
                return ResourceManager.GetString("Profile_Birth date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Code.
        /// </summary>
        public static string Profile_Calling_Code {
            get {
                return ResourceManager.GetString("Profile_Calling Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        public static string Profile_Choose {
            get {
                return ResourceManager.GetString("Profile_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Profile_Confirmation {
            get {
                return ResourceManager.GetString("Profile_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email delivery failed. Please contact system administrator..
        /// </summary>
        public static string Profile_Confirmation_email_delivery_failed__Please_contact_system_administrator_ {
            get {
                return ResourceManager.GetString("Profile_Confirmation email delivery failed. Please contact system administrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect a new provider.
        /// </summary>
        public static string Profile_Connect_a_new_provider {
            get {
                return ResourceManager.GetString("Profile_Connect a new provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer TOTP.
        /// </summary>
        public static string Profile_Developer_TOTP {
            get {
                return ResourceManager.GetString("Profile_Developer TOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ελληνικά.
        /// </summary>
        public static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing providers.
        /// </summary>
        public static string Profile_Existing_providers {
            get {
                return ResourceManager.GetString("Profile_Existing providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External providers.
        /// </summary>
        public static string Profile_External_providers {
            get {
                return ResourceManager.GetString("Profile_External providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Profile_First_name {
            get {
                return ResourceManager.GetString("Profile_First name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Profile_here {
            get {
                return ResourceManager.GetString("Profile_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have been informed about the processing of my personal data and I consent to it, as specifically defined.
        /// </summary>
        public static string Profile_I_have_been_informed_about_the_processing_of_my_personal_data_and_I_consent_to_it__as_specifically_defined {
            get {
                return ResourceManager.GetString("Profile_I have been informed about the processing of my personal data and I conse" +
                        "nt to it, as specifically defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Profile_Language {
            get {
                return ResourceManager.GetString("Profile_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Profile_Last_name {
            get {
                return ResourceManager.GetString("Profile_Last name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Profile.
        /// </summary>
        public static string Profile_Manage_Profile {
            get {
                return ResourceManager.GetString("Profile_Manage Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Profile_Phone_number {
            get {
                return ResourceManager.GetString("Profile_Phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Profile_Preferences {
            get {
                return ResourceManager.GetString("Profile_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Language.
        /// </summary>
        public static string Profile_PreferredLanguage {
            get {
                return ResourceManager.GetString("Profile_PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile_Profile {
            get {
                return ResourceManager.GetString("Profile_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Profile_Remove {
            get {
                return ResourceManager.GetString("Profile_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Profile_Save {
            get {
                return ResourceManager.GetString("Profile_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax identification.
        /// </summary>
        public static string Profile_Tax_identification {
            get {
                return ResourceManager.GetString("Profile_Tax identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string Profile_Timezone {
            get {
                return ResourceManager.GetString("Profile_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Profile_Unknown {
            get {
                return ResourceManager.GetString("Profile_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Profile_Username {
            get {
                return ResourceManager.GetString("Profile_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new email verification is still pending..
        /// </summary>
        public static string Profile_Your_new_email_verification_is_still_pending_ {
            get {
                return ResourceManager.GetString("Profile_Your new email verification is still pending.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile was updated successfully..
        /// </summary>
        public static string Profile_Your_profile_was_updated_successfully_ {
            get {
                return ResourceManager.GetString("Profile_Your profile was updated successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once complete, you may close this tab..
        /// </summary>
        public static string Redirect_CloseTab {
            get {
                return ResourceManager.GetString("Redirect_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now being returned to the application..
        /// </summary>
        public static string Redirect_Returning {
            get {
                return ResourceManager.GetString("Redirect_Returning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Register_account {
            get {
                return ResourceManager.GetString("Register_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Register_Already_have_an_account_ {
            get {
                return ResourceManager.GetString("Register_Already have an account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your.
        /// </summary>
        public static string Register_Associate_your {
            get {
                return ResourceManager.GetString("Register_Associate_your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Code.
        /// </summary>
        public static string Register_Calling_Code {
            get {
                return ResourceManager.GetString("Register_Calling Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a username and a password of your choice. You can periodically change your password or whenever you wish to..
        /// </summary>
        public static string Register_Choose_a_username_and_a_password_of_your_choice__You_can_periodically_change_your_password_or_whenever_you_wish_to_ {
            get {
                return ResourceManager.GetString("Register_Choose a username and a password of your choice. You can periodically ch" +
                        "ange your password or whenever you wish to.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an email and a password of your choice. You can periodically change your password or whenever you wish to..
        /// </summary>
        public static string Register_Choose_an_email_and_a_password_of_your_choice__You_can_periodically_change_your_password_or_whenever_you_wish_to_ {
            get {
                return ResourceManager.GetString("Register_Choose an email and a password of your choice. You can periodically chan" +
                        "ge your password or whenever you wish to.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Register_First_name {
            get {
                return ResourceManager.GetString("Register_First name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Register_here {
            get {
                return ResourceManager.GetString("Register_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I consent to the registration and processing of the above personal details for my contact and service as they are defined.
        /// </summary>
        public static string Register_I_consent_to_the_registration_and_processing_of_the_above_personal_details_for_my_contact_and_service_as_they_are_defined {
            get {
                return ResourceManager.GetString("Register_I consent to the registration and processing of the above personal detai" +
                        "ls for my contact and service as they are defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I consent to the use of my contact information, including my email address, for the purpose of receiving commercial communications, promotional materials, and marketing updates from the organization. I understand that I may withdraw my consent at any time..
        /// </summary>
        public static string Register_I_consent_to_the_use_of_my_contact_information__including_my_email_address__for_the_purpose_of_receiving_commercial_communications__promotional_materials__and_marketing_updates_from_the_organization__I_understand_that_I_may_withdraw_my_consent_at_any_time_ {
            get {
                return ResourceManager.GetString(@"Register_I consent to the use of my contact information, including my email address, for the purpose of receiving commercial communications, promotional materials, and marketing updates from the organization. I understand that I may withdraw my consent at any time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept the &lt;a href=&quot;/terms&quot; target=&quot;_blank&quot;&gt;Terms of service&lt;/a&gt; and the &lt;a href=&quot;/privacy&quot; target=&quot;_blank&quot;&gt;privacy policy&lt;/a&gt;..
        /// </summary>
        public static string Register_I_Have_Read_And_Accept_Terms {
            get {
                return ResourceManager.GetString("Register_I_Have_Read_And_Accept_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us.
        /// </summary>
        public static string Register_Join_us {
            get {
                return ResourceManager.GetString("Register_Join us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Register_Last_name {
            get {
                return ResourceManager.GetString("Register_Last name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login with.
        /// </summary>
        public static string Register_login_with {
            get {
                return ResourceManager.GetString("Register_login with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Register_OR {
            get {
                return ResourceManager.GetString("Register_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Register_Phone_number {
            get {
                return ResourceManager.GetString("Register_Phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Register {
            get {
                return ResourceManager.GetString("Register_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Register_Sign_up {
            get {
                return ResourceManager.GetString("Register_Sign up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These credentials are personal. Please remember them and do not reveal in any way (i.e orally, written, email) in third parties..
        /// </summary>
        public static string Register_These_credentials_are_personal__Please_remember_them_and_do_not_reveal_in_any_way__i_e_orally__written__email__in_third_parties_ {
            get {
                return ResourceManager.GetString("Register_These credentials are personal. Please remember them and do not reveal i" +
                        "n any way (i.e orally, written, email) in third parties.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string Register_Timezone {
            get {
                return ResourceManager.GetString("Register_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register as a new user you will need to fill in the following information..
        /// </summary>
        public static string Register_To_register_as_a_new_user_you_will_need_to_fill_in_the_following_information {
            get {
                return ResourceManager.GetString("Register_To_register_as_a_new_user_you_will_need_to_fill_in_the_following_informa" +
                        "tion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Register_Username {
            get {
                return ResourceManager.GetString("Register_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting UI language....
        /// </summary>
        public static string SetLanguage_Setting_ui_language {
            get {
                return ResourceManager.GetString("SetLanguage_Setting_ui_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string VerifyPhone_Code {
            get {
                return ResourceManager.GetString("VerifyPhone_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string VerifyPhone_Next {
            get {
                return ResourceManager.GetString("VerifyPhone_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is valid till:.
        /// </summary>
        public static string VerifyPhone_OTP_is_valid_till {
            get {
                return ResourceManager.GetString("VerifyPhone_OTP_is_valid_till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string VerifyPhone_Resend {
            get {
                return ResourceManager.GetString("VerifyPhone_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string VerifyPhone_Save {
            get {
                return ResourceManager.GetString("VerifyPhone_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify phone number.
        /// </summary>
        public static string VerifyPhone_Verify_phone_number {
            get {
                return ResourceManager.GetString("VerifyPhone_Verify phone number", resourceCulture);
            }
        }
    }
}
