<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
  </ItemGroup>
</Project>
