using Indice.Features.Agents.Core.Data;
using Microsoft.EntityFrameworkCore;

namespace Indice.Features.Agents.Core;

/// <summary>Root options for the Dex RAG template. Bound from the <c>Dex</c> configuration section.</summary>
public class AgentsOptions
{
    /// <summary>Default embedding vector dimensionality used when a deployment-specific value is not configured.</summary>
    public const int EmbeddingDimensionsDefault = 1536;

    /// <summary>Azure OpenAI connection and deployment configuration.</summary>
    public AzureOpenAIOptions AzureOpenAI { get; set; } = new();

    /// <summary>Per-role model invocation parameters (temperature, output token cap).</summary>
    public ModelsOptions Models { get; set; } = new();

    /// <summary>Retrieval-time knobs (TopK, TopN, query expansion).</summary>
    public RetrievalOptions Retrieval { get; set; } = new();

    /// <summary>Pipeline-level feature flags.</summary>
    public PipelineOptions Pipeline { get; set; } = new();

    /// <summary>Chat session behavior (history window, title auto-generation).</summary>
    public SessionOptions Session { get; set; } = new();

    /// <summary>Ingestion-time knobs (root path, chunk sizes, embedding batch size).</summary>
    public IngestionOptions Ingestion { get; set; } = new();

    /// <summary>Allowed categorical/language values constrained by the host application.</summary>
    public TaxonomyOptions Taxonomy { get; set; } = new();

    /// <summary>
    /// Optional callback to configure the <see cref="DbContextOptionsBuilder"/> for the <see cref="AgentsDbContext"/>.
    /// </summary>
    public Action<IServiceProvider, DbContextOptionsBuilder>? ConfigureDbContext { get; set; }
    /// <summary>Azure OpenAI service endpoint, credentials, and per-role deployment names.</summary>
    public class AzureOpenAIOptions
    {
        /// <summary>Azure OpenAI resource endpoint, e.g. <c>https://my-resource.openai.azure.com</c>.</summary>
        public string? Endpoint { get; set; }

        /// <summary>API key. Prefer Managed Identity in production; this template uses keys for simplicity.</summary>
        public string? ApiKey { get; set; }

        /// <summary>Deployment names per role.</summary>
        public AzureOpenAIDeployments Deployments { get; set; } = new();

        /// <summary>Dimensionality of the embedding model in use.</summary>
        public int EmbeddingDimensions { get; set; } = EmbeddingDimensionsDefault;
    }

    /// <summary>Role-bound Azure OpenAI deployment names.</summary>
    public class AzureOpenAIDeployments
    {
        /// <summary>Strong reasoning deployment used for intent classification and final answer composition.</summary>
        public string? Reasoning { get; set; }

        /// <summary>Fast/cheap deployment used for query rewriting and reranking.</summary>
        public string? Fast { get; set; }

        /// <summary>Embedding deployment used for chunk and query vectorization.</summary>
        public string? Embedding { get; set; }
    }

    /// <summary>Per-role model invocation parameters applied by the pipeline steps when calling their chat model.</summary>
    public class ModelsOptions
    {
        /// <summary>Parameters for the reasoning deployment (intent classification, answer composition).</summary>
        public ModelParametersOptions Reasoning { get; set; } = new();

        /// <summary>Parameters for the fast deployment (query rewriting, reranking).</summary>
        public ModelParametersOptions Fast { get; set; } = new();
    }

    /// <summary>Invocation parameters for a single model role.</summary>
    public class ModelParametersOptions
    {
        /// <summary>Sampling temperature in [0, 2]. The default 0 keeps pipeline outputs as deterministic as the model allows.</summary>
        public float Temperature { get; set; } = 0.0f;

        /// <summary>Optional cap on tokens generated per call; <c>null</c> leaves the provider default.</summary>
        public int? MaxOutputTokens { get; set; }
    }

    /// <summary>Retrieval-time knobs.</summary>
    public class RetrievalOptions
    {
        /// <summary>Number of candidates retrieved per rewritten query before reranking.</summary>
        public int TopK { get; set; } = 10;

        /// <summary>Number of candidates kept after reranking and passed to the composer.</summary>
        public int TopN { get; set; } = 5;

        /// <summary>Number of query rewrites generated by the rewrite step (1 means the original question only).</summary>
        public int QueryExpansion { get; set; } = 2;

        /// <summary>Optional minimum similarity score below which candidates are discarded.</summary>
        public double MinScore { get; set; } = 0.1;

        /// <summary>Maximum characters of each candidate's content included in the rerank prompt — bounds prompt size and cost.</summary>
        public int RerankSnippetLength { get; set; } = 240;
    }

    /// <summary>Pipeline-level feature flags.</summary>
    public class PipelineOptions
    {
        /// <summary>When false, the reranker step is skipped and embedding-similarity order is preserved.</summary>
        public bool EnableRerank { get; set; } = true;

        /// <summary>When false, the rewrite step is skipped and the original question is used verbatim. Note: rewriting is also what condenses follow-up questions into standalone retrieval queries using the conversation history — disabling it degrades multi-turn retrieval.</summary>
        public bool EnableQueryRewrite { get; set; } = true;

        /// <summary>When true, the composer is instructed to refuse answers that cannot be grounded in retrieved context.</summary>
        public bool StrictGrounding { get; set; } = true;
    }

    /// <summary>Chat session behavior.</summary>
    public class SessionOptions
    {
        /// <summary>Number of recent turns (user + assistant message pairs) loaded into the RAG pipeline and returned on session-detail reads. Each turn maps to two persisted messages.</summary>
        public int HistoryWindow { get; set; } = 5;

        /// <summary>When true, the session title is auto-generated from the first user message.</summary>
        public bool TitleAutoGenerate { get; set; } = true;
    }

    /// <summary>Ingestion-time knobs.</summary>
    public class IngestionOptions
    {
        /// <summary>Filesystem root (relative to the content root) used to resolve ingestion paths.</summary>
        public string RootPath { get; set; } = "seed/docs";

        /// <summary>Target chunk size in tokens.</summary>
        public int ChunkTargetTokens { get; set; } = 256;

        /// <summary>Overlap between adjacent chunks in tokens.</summary>
        public int ChunkOverlapTokens { get; set; } = 50;

        /// <summary>Maximum inputs per embedding call.</summary>
        public int EmbedBatchSize { get; set; } = 10;

        /// <summary>Maximum number of attempts.</summary>
        public int MaxRetries { get; set; } = 3;

        /// <summary>Delays between retry attempts.</summary>
        public TimeSpan[] RetryDelays { get; set; } = new[] { TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(2), TimeSpan.FromSeconds(4) };

        /// <summary>When false, ingestion is skipped and the database is left as-is.</summary>
        public bool Enabled { get; set; } = true;
    }

    /// <summary>
    /// Allowed categorical / language values constrained by the host application.
    /// The intent classifier is instructed to pick one value from each list and validate against it
    /// before populating retrieval filters. Edit per client; no migration needed.
    /// </summary>
    public class TaxonomyOptions
    {
        /// <summary>Allowed document categories. Used as the retrieval filter domain and to constrain the intent classifier's category output.</summary>
        public IReadOnlyList<string> Categories { get; set; } = ["general", "policy", "faq"];

        /// <summary>Allowed ISO-639-1 (or BCP-47) language codes.</summary>
        public IReadOnlyList<string> Languages { get; set; } = ["en", "el"];
    }
}


