using Indice.Features.Agents.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.AI;

namespace Indice.Features.Agents.Core;

/// <summary>Root options for the Dex RAG template. Bound from the <c>Dex</c> configuration section.</summary>
public class AgentsOptions
{
    /// <summary>Default embedding vector dimensionality used when a deployment-specific value is not configured.</summary>
    public const int EmbeddingDimensionsDefault = 1536;

    /// <summary>Azure OpenAI connection and deployment configuration.</summary>
    public AzureOpenAIOptions AzureOpenAI { get; set; } = new();

    /// <summary>Retrieval-time knobs (NumberOfCandidates, NumberOfResults, query expansion, etc).</summary>
    public RetrievalOptions Retrieval { get; set; } = new();

    /// <summary>Pipeline-level feature flags.</summary>
    public DefaultPipelineOptions Pipeline { get; set; } = new();

    /// <summary>Chat session behavior (history window, title auto-generation).</summary>
    public SessionOptions Session { get; set; } = new();

    /// <summary>Ingestion-time knobs (root path, chunk sizes, embedding batch size).</summary>
    public IngestionOptions Ingestion { get; set; } = new();

    /// <summary>Allowed categorical/language values constrained by the host application.</summary>
    public TaxonomyOptions Taxonomy { get; set; } = new();

    /// <summary>External MCP server endpoints whose tools are injected into the answer-composer step.</summary>
    public ExternalMcpOptions ExternalMcp { get; set; } = new();

    /// <summary>
    /// Optional callback to configure the <see cref="DbContextOptionsBuilder"/> for the <see cref="AgentsDbContext"/>.
    /// </summary>
    public Action<IServiceProvider, DbContextOptionsBuilder>? ConfigureDbContext { get; set; }

    /// <summary>
    /// Optional callback to configure the standalone <see cref="ModelsOptions"/> (per-role <see cref="ChatOptions"/>
    /// and universal tools). Applied after <c>Dex:Models</c> configuration binding when <see cref="ModelsOptions"/>
    /// is resolved. Use it to register tools shared across pipeline steps.
    /// </summary>
    public Action<ModelsOptions>? ConfigureModelOptions { get; set; }

    /// <summary>Azure OpenAI service endpoint, credentials, and per-role deployment names.</summary>
    public class AzureOpenAIOptions
    {
        /// <summary>Azure OpenAI resource endpoint, e.g. <c>https://my-resource.openai.azure.com</c>.</summary>
        public string? Endpoint { get; set; }

        /// <summary>API key. Prefer Managed Identity in production; this template uses keys for simplicity.</summary>
        public string? ApiKey { get; set; }

        /// <summary>Deployment names per role.</summary>
        public AzureOpenAIDeployments Deployments { get; set; } = new();

        /// <summary>Dimensionality of the embedding model in use.</summary>
        public int EmbeddingDimensions { get; set; } = EmbeddingDimensionsDefault;
    }

    /// <summary>Role-bound Azure OpenAI deployment names.</summary>
    public class AzureOpenAIDeployments
    {
        /// <summary>Strong reasoning deployment used for intent classification and final answer composition.</summary>
        public string? Reasoning { get; set; }

        /// <summary>Fast/cheap deployment used for query rewriting and reranking.</summary>
        public string? Fast { get; set; }

        /// <summary>Embedding deployment used for chunk and query vectorization.</summary>
        public string? Embedding { get; set; }
    }
    /// <summary>Retrieval-time knobs.</summary>
    public class RetrievalOptions
    {
        /// <summary>Number of candidates retrieved per rewritten query before reranking.</summary>
        public int NumberOfCandidates { get; set; } = 10;

        /// <summary>Number of top candidates returned to the composer after reranking.</summary>
        public int NumberOfResults { get; set; } = 5;

        /// <summary>Number of query rewrites generated by the rewrite step (1 means the original question only).</summary>
        public int QueryExpansion { get; set; } = 2;

        /// <summary>Optional minimum similarity score below which candidates are discarded.</summary>
        public double MinScore { get; set; } = 0.2;

        /// <summary>Maximum characters of each candidate's content included in the rerank prompt — bounds prompt size and cost.</summary>
        public int RerankSnippetLength { get; set; } = 240;
    }

    /// <summary>Pipeline-level feature flags.</summary>
    public class DefaultPipelineOptions
    {
        /// <summary>When false, the reranker step is skipped and embedding-similarity order is preserved.</summary>
        public bool EnableRerank { get; set; } = true;

        /// <summary>When false, the rewrite step is skipped and the original question is used verbatim. Note: rewriting is also what condenses follow-up questions into standalone retrieval queries using the conversation history — disabling it degrades multi-turn retrieval.</summary>
        public bool EnableQueryRewrite { get; set; } = true;

        /// <summary>When true, the composer is instructed to refuse answers that cannot be grounded in retrieved context.</summary>
        public bool StrictGrounding { get; set; } = true;
    }

    /// <summary>Chat session behavior.</summary>
    public class SessionOptions
    {
        /// <summary>Number of recent turns (user + assistant message pairs) loaded into the RAG pipeline and returned on session-detail reads. Each turn maps to two persisted messages.</summary>
        public int HistoryWindow { get; set; } = 5;

        /// <summary>When true, the session title is auto-generated from the first user message.</summary>
        public bool TitleAutoGenerate { get; set; } = true;
    }

    /// <summary>Ingestion-time knobs.</summary>
    public class IngestionOptions
    {
        /// <summary>Target chunk size in tokens.</summary>
        public int ChunkTargetTokens { get; set; } = 256;

        /// <summary>Overlap between adjacent chunks in tokens.</summary>
        public int ChunkOverlapTokens { get; set; } = 50;

        /// <summary>Maximum inputs per embedding call.</summary>
        public int EmbedBatchSize { get; set; } = 10;

        /// <summary>When false, ingestion is skipped and the database is left as-is.</summary>
        public bool Enabled { get; set; } = true;
    }

    /// <summary>
    /// Allowed categorical / language values constrained by the host application.
    /// The intent classifier is instructed to pick one value from each list and validate against it
    /// before populating retrieval filters. Edit per client; no migration needed.
    /// </summary>
    public class TaxonomyOptions
    {
        /// <summary>Allowed document categories. Used as the retrieval filter domain and to constrain the intent classifier's category output.</summary>
        public IReadOnlyList<string> Categories { get; set; } = ["policy", "faq", "identity", "purpose_of_agent", "message"];

        /// <summary>Allowed ISO-639-1 (or BCP-47) language codes.</summary>
        public IReadOnlyList<string> Languages { get; set; } = ["en", "el", "de", "fr", "es"];
    }

    /// <summary>
    /// External MCP server endpoints whose tools are injected into the answer-composer step.
    /// Leave <see cref="Servers"/> empty to disable external tool calling.
    /// </summary>
    public class ExternalMcpOptions
    {
        /// <summary>
        /// Streamable-HTTP MCP servers to connect to. Leave empty to disable external tool calling.
        /// </summary>
        public IReadOnlyList<ExternalMcpServer> Servers { get; set; } = [];
    }

    /// <summary>Describes a single external MCP server to connect to.</summary>
    public class ExternalMcpServer
    {
        /// <summary>
        /// Streamable-HTTP endpoint URL of the external MCP server (e.g. <c>https://server/mcp</c>).
        /// </summary>
        public required string Url { get; set; }

        /// <summary>
        /// Optional static bearer token sent as <c>Authorization: Bearer &lt;token&gt;</c> on every request.
        /// Leave <see langword="null"/> for unauthenticated servers.
        /// </summary>
        public string? BearerToken { get; set; }
        /// OAuth2 client-credentials config. Takes precedence over BearerToken when set.
        public ClientCredentialsOptions? OAuth { get; set; }

        /// <summary>Oauth client credentials configuration for the external MCP server. Takes precedence over <see cref="BearerToken"/> when set.</summary>
        public class ClientCredentialsOptions
        {
            /// <summary>OAuth2 token endpoint URL (e.g. <c>https://server/oauth2/token</c>).</summary>
            public required string TokenEndpoint { get; set; }
            /// <summary>OAuth2 client ID.</summary>
            public required string ClientId { get; set; }
            /// <summary>OAuth2 client secret.</summary>
            public required string ClientSecret { get; set; }
            /// <summary>OAuth2 scope.</summary>
            public string? Scope { get; set; }
        }
    }
}

/// <summary>
/// Per-role model invocation parameters applied by the pipeline steps when calling their chat model.
/// Each role is a <see cref="ChatOptions"/>: <c>Temperature</c> and <c>MaxOutputTokens</c> bind from
/// configuration; <c>Tools</c> and the remaining knobs are set in code. Steps <see cref="ChatOptions.Clone"/>
/// the role options before adding per-step instructions.
/// </summary>
public class ModelsOptions
{
    /// <summary>Options for the reasoning deployment (intent classification, answer composition). Temperature defaults to 0 to keep pipeline outputs as deterministic as the model allows.</summary>
    public ChatOptions BaseReasoningModelOptions { get; set; } = new() { Temperature = 0.0f, ToolMode = AutoChatToolMode.Auto, MaxOutputTokens = 2048, Tools = Array.Empty<AITool>() };

    /// <summary>Options for the fast deployment (query rewriting, reranking). Temperature defaults to 0 to keep pipeline outputs as deterministic as the model allows.</summary>
    public ChatOptions BaseFastModelOptions { get; set; } = new() { Temperature = 0.0f };
}



