//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indice.Features.Agents.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indice.Features.Agents.Core.AgentResources", typeof(AgentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP code is invalid. You have reached the maximum number of attempts. Please start again..
        /// </summary>
        internal static string InvalidOtpMaxAttemptsReachedMessage {
            get {
                return ResourceManager.GetString("InvalidOtpMaxAttemptsReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That OTP was not valid. Please try again ({0} attempt(s) left).&quot;.
        /// </summary>
        internal static string InvalidOtpRetryMessage {
            get {
                return ResourceManager.GetString("InvalidOtpRetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t receive an OTP code. Please enter the OTP sent to your phone..
        /// </summary>
        internal static string OtpInputValidationEmpty {
            get {
                return ResourceManager.GetString("OtpInputValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification code was send to {0}. Please enter the OTP you received..
        /// </summary>
        internal static string OtpVerificationCodeSendMessage {
            get {
                return ResourceManager.GetString("OtpVerificationCodeSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtvpVerificationFailedMessage.
        /// </summary>
        internal static string OtvpVerificationFailedMessage {
            get {
                return ResourceManager.GetString("OtvpVerificationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP is valid.
        /// </summary>
        internal static string OtvpVerificationSuccessMessage {
            get {
                return ResourceManager.GetString("OtvpVerificationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sadas.
        /// </summary>
        internal static string OwnershipRetryPrompt {
            get {
                return ResourceManager.GetString("OwnershipRetryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type the you phone number to complete the verification process.
        /// </summary>
        internal static string OwnershipVerificationMessagePrompt {
            get {
                return ResourceManager.GetString("OwnershipVerificationMessagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification failed. Maximum {0} attempts reached. Please try again later..
        /// </summary>
        internal static string VerificationFailedMaxAttempts {
            get {
                return ResourceManager.GetString("VerificationFailedMaxAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information provided does not match our records. Attempt {0} of {1}. Please try again..
        /// </summary>
        internal static string VerificationFailedRetry {
            get {
                return ResourceManager.GetString("VerificationFailedRetry", resourceCulture);
            }
        }
    }
}
