<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFrameworks></TargetFrameworks>
    <TargetFramework>net10.0</TargetFramework>
    <VersionPrefix>$(VersionPrefixAgents)</VersionPrefix>
    <VersionSuffix>beta04</VersionSuffix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Indice.EntityFrameworkCore" Version="$(VersionPrefixCore)-*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.11.0" />
    <PackageReference Include="Microsoft.Agents.AI.Abstractions" Version="1.11.0" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.11.0" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.11.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.7.0" />
    <!-- 3rd Party -->
    <PackageReference Include="Duende.IdentityModel" Version="8.1.0" />
    <PackageReference Include="Handlebars.Net" Version="2.1.6" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.5.0-beta.1" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
  </ItemGroup>

</Project>
