using System.Reflection;
using Elsa.Activities.Email;
using Elsa.Activities.Email.Options;
using Elsa.Retention.Contracts;
using Elsa.Retention.Options;
using Elsa.Retention.Specifications;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Indice.Features.Cases.Workflows;

/// <summary>Cases workflow Options and settings</summary>
public class CasesWorkflowOptions
{
    /// <summary>creates default options</summary>
    public CasesWorkflowOptions() { }


    /// <summary>creates default options with the ability to register custom services</summary>
    public CasesWorkflowOptions(IServiceCollection services) {
        Services = services ?? throw new ArgumentNullException(nameof(services));
    }

    internal IServiceCollection Services { get; set; } = null!;

    /// <summary>
    /// Configuration <see cref="Action"/> for internal <see cref="DbContext"/>. 
    /// If not provided the underlying store defaults to SQL Server expecting the setting <i>ConnectionStrings:DefaultConnection</i> to be present.
    /// </summary>
    public Action<IServiceProvider, DbContextOptionsBuilder>? ConfigureDbContext { get; set; }

    /// <summary>
    /// Configure SMTP options for the <see cref="SendEmail"/> activity.
    /// </summary>
    public Action<SmtpOptions>? ConfigureSmtp { get; set; }
    /// <summary>
    /// Configure RetentionServices options.
    /// </summary>
    public Action<CleanupOptions>? ConfigureRetentionServices { get; set; }

    /// <summary>Controls the registration of the retention services</summary>
    public bool RetentionServicesEnabled { get; set; } = true;

    /// <summary>
    /// The assembly with the workflow activities and definitions to register.
    /// </summary>
    public Func<Assembly>? GetWorkflowAssembly { get; set; }

    /// <summary>
    /// Override the specification filter that will select the workflows for deletion. If the value is null the default <see cref="CompletedWorkflowFilterSpecification"/> will be used.
    /// </summary>
    public IRetentionSpecificationFilter? RetentionSpecificationFilter { get; set; }

    /// <summary>Workflow Api path</summary>
    [Obsolete("Will be removed in future versions. Use ServerHttpActivitiesBasePath to configure Elsa HttpActivity.")]
    public string? ServerBasePath {
        get => ServerHttpActivitiesBasePath;
        set => ServerHttpActivitiesBasePath = value;
    }

    /// <summary>
    /// The root path at which HTTP activities can be invoked. Defaults to <c>/http-activities</c>.
    /// <remarks>
    /// Elsa Middleware: <see cref="Elsa.Activities.Http.Middleware.HttpEndpointMiddleware"/>.
    /// Elsa Http Activity: <see cref="Elsa.Activities.Http.HttpEndpoint"/>.
    /// </remarks>
    /// </summary>
    public string? ServerHttpActivitiesBasePath { get; set; } = "/http-activities";

    /// <summary>
    /// The base URL of the server. This should be set to the same value at which the Elsa Server is publicly available.
    /// It will be used when generating absolute URLs need to be generated by activities such as SendEmail. 
    /// </summary>
    public string? ServerBaseUrl { get; set; }

    /// <summary>Register static file middleware. Used for Disigner ui assets comming from staticweb assets dll to work</summary>
    /// <remarks>Set to false if already registered in host assembly so that <strong>UseStaticFiles</strong> is not called twice.</remarks>
    public bool RegisterStaticFiles { get; set; } = true;
    /// <summary>Maps controllers in the application builder. </summary>
    /// <remarks>Set to false if already working with controllers so <strong>MapControllers</strong> is not called twice.</remarks>
    public bool RegisterControllers { get; set; } = true;
    /// <summary>Adds <strong>OpenIdConnect</strong> authentication for the UI and api controllers</summary>
    /// <remarks>Set to false to allow anonymous access.</remarks>
    public bool RegisterAuthentication { get; set; } = true;
    /// <summary>
    /// The client id of the UI client that will be used to authenticate with the server.
    /// </summary>
    public string WorkflowUIClientId { get; set; } = "cases-ui";
}
