<Project>
  <PropertyGroup Label="Assembly Common">
    <Copyright>Copyright (c) 2018 Indice</Copyright>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <!--<TargetFramework></TargetFramework>-->

    <VersionPrefixMajor>8</VersionPrefixMajor>
    <VersionPrefixBase>$(VersionPrefixMajor).47</VersionPrefixBase>

    <VersionPrefixCore>$(VersionPrefixBase).3</VersionPrefixCore>
    <VersionPrefixIdentity>$(VersionPrefixBase).3</VersionPrefixIdentity>
    <VersionPrefixIdentityUI>$(VersionPrefixBase).3</VersionPrefixIdentityUI>
    <VersionPrefixCases>$(VersionPrefixBase).3</VersionPrefixCases>
    <VersionPrefixMessages>$(VersionPrefixBase).3</VersionPrefixMessages>
    <VersionPrefixMultitenancy>$(VersionPrefixBase).3</VersionPrefixMultitenancy>
    <VersionPrefixRisk>$(VersionPrefixBase).3</VersionPrefixRisk>
    <VersionPrefixMedia>$(VersionPrefixBase).3</VersionPrefixMedia>
    <VersionPrefixGeoIP>$(VersionPrefixBase).3</VersionPrefixGeoIP>
    <VersionPrefixGovGr>$(VersionPrefixBase).3</VersionPrefixGovGr>
    <VersionPrefixAspNet>$(VersionPrefixBase).3</VersionPrefixAspNet>
    <VersionPrefixActivityLogs>$(VersionPrefixBase).3</VersionPrefixActivityLogs>
    <VersionPrefixFtpServer>$(VersionPrefixBase).3</VersionPrefixFtpServer>
    <VersionPrefix>$(VersionPrefixBase).3</VersionPrefix>

    <!--<VersionSuffix>rc06</VersionSuffix>-->
    <Authors>Constantinos Leftheris</Authors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>Latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>
  <PropertyGroup Label="Package Common">
    <PackageReleaseNotes></PackageReleaseNotes>
    <PackageTags></PackageTags>
    <IsPackable>true</IsPackable>
    <PackageIcon>icon-310.png</PackageIcon>
    <PackageProjectUrl>https://github.com/indice-co/Indice.Platform</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/indice-co/Indice.Platform</RepositoryUrl>
    <Company>Indice</Company>
    <!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
    <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
