//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const RISK_API_BASE_URL = new InjectionToken<string>('RISK_API_BASE_URL');

export interface IRiskApiService {
    /**
     * Calculates the risk given a transaction presented in the system.
     * @return OK
     */
    getRisk(body: RiskModel): Observable<AggregateRuleExecutionResult>;
    /**
     * Fetch risk events.
     * @param page (optional) The current page of the list. Default is 1.
     * @param size (optional) The size of the list. Default is 100
     * @param sort (optional) The sort order plus the sort direction of the list. for example displayName-
     * @param search (optional) A search term used to limit the results of the list.
     * @return OK
     */
    getRiskEvents(filter: string[], page?: number | null | undefined, size?: number | null | undefined, sort?: string | null | undefined, search?: string | null | undefined): Observable<RiskEventResultSet>;
    /**
     * Fetch risk events by session id.
     * @return OK
     */
    getRiskEventBySessionId(sessionId: string): Observable<RiskEvent[]>;
    /**
     * Fetch risk results.
     * @param page (optional) The current page of the list. Default is 1.
     * @param size (optional) The size of the list. Default is 100
     * @param sort (optional) The sort order plus the sort direction of the list. for example displayName-
     * @param search (optional) A search term used to limit the results of the list.
     * @return OK
     */
    getRiskResults(filter: string[], page?: number | null | undefined, size?: number | null | undefined, sort?: string | null | undefined, search?: string | null | undefined): Observable<DbAggregateRuleExecutionResultResultSet>;
    /**
     * Fetch the configuration options given a rule name.
     * @return OK
     */
    getRiskRuleOptions(ruleName: string): Observable<{ [key: string]: string; }>;
    /**
     * Update the configuration options given a rule name.
     * @param body (optional) 
     * @return No Content
     */
    updateRiskRuleOptions(ruleName: string, body?: ChaniaRuleOptions | null | undefined): Observable<void>;
    /**
     * Fetch registered risk rules.
     * @return OK
     */
    getRiskRules(): Observable<RiskRuleDtoResultSet>;
    /**
     * Records a risk event in the store.
     * @return Created
     */
    createRiskEvent(body: RiskModel): Observable<void>;
}

@Injectable({
    providedIn: 'root'
})
export class RiskApiService implements IRiskApiService {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(RISK_API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Calculates the risk given a transaction presented in the system.
     * @return OK
     */
    getRisk(body: RiskModel): Observable<AggregateRuleExecutionResult> {
        let url_ = this.baseUrl + "/api/risk";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRisk(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRisk(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<AggregateRuleExecutionResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<AggregateRuleExecutionResult>;
        }));
    }

    protected processGetRisk(response: HttpResponseBase): Observable<AggregateRuleExecutionResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AggregateRuleExecutionResult.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = HttpValidationProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Fetch risk events.
     * @param page (optional) The current page of the list. Default is 1.
     * @param size (optional) The size of the list. Default is 100
     * @param sort (optional) The sort order plus the sort direction of the list. for example displayName-
     * @param search (optional) A search term used to limit the results of the list.
     * @return OK
     */
    getRiskEvents(filter: string[], page?: number | null | undefined, size?: number | null | undefined, sort?: string | null | undefined, search?: string | null | undefined): Observable<RiskEventResultSet> {
        let url_ = this.baseUrl + "/api/risk-events?";
        if (filter === undefined || filter === null)
            throw new globalThis.Error("The parameter 'filter' must be defined and cannot be null.");
        else
            filter && filter.forEach(item => { url_ += "Filter=" + encodeURIComponent("" + item) + "&"; });
        if (page !== undefined && page !== null)
            url_ += "Page=" + encodeURIComponent("" + page) + "&";
        if (size !== undefined && size !== null)
            url_ += "Size=" + encodeURIComponent("" + size) + "&";
        if (sort !== undefined && sort !== null)
            url_ += "Sort=" + encodeURIComponent("" + sort) + "&";
        if (search !== undefined && search !== null)
            url_ += "Search=" + encodeURIComponent("" + search) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRiskEvents(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRiskEvents(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<RiskEventResultSet>;
                }
            } else
                return _observableThrow(response_) as any as Observable<RiskEventResultSet>;
        }));
    }

    protected processGetRiskEvents(response: HttpResponseBase): Observable<RiskEventResultSet> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = RiskEventResultSet.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Fetch risk events by session id.
     * @return OK
     */
    getRiskEventBySessionId(sessionId: string): Observable<RiskEvent[]> {
        let url_ = this.baseUrl + "/api/risk-events/session/{sessionId}";
        if (sessionId === undefined || sessionId === null)
            throw new globalThis.Error("The parameter 'sessionId' must be defined.");
        url_ = url_.replace("{sessionId}", encodeURIComponent("" + sessionId));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRiskEventBySessionId(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRiskEventBySessionId(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<RiskEvent[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<RiskEvent[]>;
        }));
    }

    protected processGetRiskEventBySessionId(response: HttpResponseBase): Observable<RiskEvent[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(RiskEvent.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Fetch risk results.
     * @param page (optional) The current page of the list. Default is 1.
     * @param size (optional) The size of the list. Default is 100
     * @param sort (optional) The sort order plus the sort direction of the list. for example displayName-
     * @param search (optional) A search term used to limit the results of the list.
     * @return OK
     */
    getRiskResults(filter: string[], page?: number | null | undefined, size?: number | null | undefined, sort?: string | null | undefined, search?: string | null | undefined): Observable<DbAggregateRuleExecutionResultResultSet> {
        let url_ = this.baseUrl + "/api/risk-results?";
        if (filter === undefined || filter === null)
            throw new globalThis.Error("The parameter 'filter' must be defined and cannot be null.");
        else
            filter && filter.forEach(item => { url_ += "Filter=" + encodeURIComponent("" + item) + "&"; });
        if (page !== undefined && page !== null)
            url_ += "Page=" + encodeURIComponent("" + page) + "&";
        if (size !== undefined && size !== null)
            url_ += "Size=" + encodeURIComponent("" + size) + "&";
        if (sort !== undefined && sort !== null)
            url_ += "Sort=" + encodeURIComponent("" + sort) + "&";
        if (search !== undefined && search !== null)
            url_ += "Search=" + encodeURIComponent("" + search) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRiskResults(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRiskResults(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DbAggregateRuleExecutionResultResultSet>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DbAggregateRuleExecutionResultResultSet>;
        }));
    }

    protected processGetRiskResults(response: HttpResponseBase): Observable<DbAggregateRuleExecutionResultResultSet> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DbAggregateRuleExecutionResultResultSet.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Fetch the configuration options given a rule name.
     * @return OK
     */
    getRiskRuleOptions(ruleName: string): Observable<{ [key: string]: string; }> {
        let url_ = this.baseUrl + "/api/risk-rule/{ruleName}";
        if (ruleName === undefined || ruleName === null)
            throw new globalThis.Error("The parameter 'ruleName' must be defined.");
        url_ = url_.replace("{ruleName}", encodeURIComponent("" + ruleName));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRiskRuleOptions(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRiskRuleOptions(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<{ [key: string]: string; }>;
                }
            } else
                return _observableThrow(response_) as any as Observable<{ [key: string]: string; }>;
        }));
    }

    protected processGetRiskRuleOptions(response: HttpResponseBase): Observable<{ [key: string]: string; }> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200) {
                result200 = {} as any;
                for (let key in resultData200) {
                    if (resultData200.hasOwnProperty(key))
                        (result200 as any)![key] = resultData200[key] !== undefined ? resultData200[key] : null as any;
                }
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Not Found", status, _responseText, _headers);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Update the configuration options given a rule name.
     * @param body (optional) 
     * @return No Content
     */
    updateRiskRuleOptions(ruleName: string, body?: ChaniaRuleOptions | null | undefined): Observable<void> {
        let url_ = this.baseUrl + "/api/risk-rule/{ruleName}";
        if (ruleName === undefined || ruleName === null)
            throw new globalThis.Error("The parameter 'ruleName' must be defined.");
        url_ = url_.replace("{ruleName}", encodeURIComponent("" + ruleName));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateRiskRuleOptions(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateRiskRuleOptions(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processUpdateRiskRuleOptions(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = HttpValidationProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Fetch registered risk rules.
     * @return OK
     */
    getRiskRules(): Observable<RiskRuleDtoResultSet> {
        let url_ = this.baseUrl + "/api/risk-rules";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRiskRules(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRiskRules(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<RiskRuleDtoResultSet>;
                }
            } else
                return _observableThrow(response_) as any as Observable<RiskRuleDtoResultSet>;
        }));
    }

    protected processGetRiskRules(response: HttpResponseBase): Observable<RiskRuleDtoResultSet> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = RiskRuleDtoResultSet.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Records a risk event in the store.
     * @return Created
     */
    createRiskEvent(body: RiskModel): Observable<void> {
        let url_ = this.baseUrl + "/api/risk/events";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateRiskEvent(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateRiskEvent(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processCreateRiskEvent(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 201) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            }));
        } else if (status === 403) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class AggregateRuleExecutionResult implements IAggregateRuleExecutionResult {
    readonly id?: string | undefined;
    readonly numberOfRulesExecuted?: number | undefined;
    readonly results?: RuleExecutionResult[] | undefined;
    readonly riskScore?: number | undefined;
    riskLevel?: RiskLevel | undefined;

    constructor(data?: IAggregateRuleExecutionResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            (this as any).id = _data["id"];
            (this as any).numberOfRulesExecuted = _data["numberOfRulesExecuted"];
            if (Array.isArray(_data["results"])) {
                (this as any).results = [] as any;
                for (let item of _data["results"])
                    (this as any).results!.push(RuleExecutionResult.fromJS(item));
            }
            (this as any).riskScore = _data["riskScore"];
            this.riskLevel = _data["riskLevel"];
        }
    }

    static fromJS(data: any): AggregateRuleExecutionResult {
        data = typeof data === 'object' ? data : {};
        let result = new AggregateRuleExecutionResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["numberOfRulesExecuted"] = this.numberOfRulesExecuted;
        if (Array.isArray(this.results)) {
            data["results"] = [];
            for (let item of this.results)
                data["results"].push(item ? item.toJSON() : undefined as any);
        }
        data["riskScore"] = this.riskScore;
        data["riskLevel"] = this.riskLevel;
        return data;
    }
}

export interface IAggregateRuleExecutionResult {
    id?: string | undefined;
    numberOfRulesExecuted?: number | undefined;
    results?: RuleExecutionResult[] | undefined;
    riskScore?: number | undefined;
    riskLevel?: RiskLevel | undefined;
}

export class ChaniaRuleOptions implements IChaniaRuleOptions {
    friendlyName?: string | undefined;
    description?: string | undefined;
    enabled?: boolean | undefined;
    eligibleEvents?: string[] | undefined;

    protected _discriminator: string;

    constructor(data?: IChaniaRuleOptions) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        this._discriminator = "ChaniaRuleOptions";
    }

    init(_data?: any) {
        if (_data) {
            this.friendlyName = _data["friendlyName"];
            this.description = _data["description"];
            this.enabled = _data["enabled"];
            if (Array.isArray(_data["eligibleEvents"])) {
                this.eligibleEvents = [] as any;
                for (let item of _data["eligibleEvents"])
                    this.eligibleEvents!.push(item);
            }
        }
    }

    static fromJS(data: any): ChaniaRuleOptions {
        data = typeof data === 'object' ? data : {};
        if (data["name"] === "AvailableBalanceRuleOptions") {
            let result = new AvailableBalanceRuleOptions();
            result.init(data);
            return result;
        }
        if (data["name"] === "HistoricalTransactionsOverMinimumAmountRuleOptions") {
            let result = new HistoricalTransactionsOverMinimumAmountRuleOptions();
            result.init(data);
            return result;
        }
        if (data["name"] === "MuleAccountRuleOptions") {
            let result = new MuleAccountRuleOptions();
            result.init(data);
            return result;
        }
        if (data["name"] === "PasswordChangedRecentlyRuleOptions") {
            let result = new PasswordChangedRecentlyRuleOptions();
            result.init(data);
            return result;
        }
        if (data["name"] === "TransactionOverMinimumAmountRuleOptions") {
            let result = new TransactionOverMinimumAmountRuleOptions();
            result.init(data);
            return result;
        }
        if (data["name"] === "UnusedAccountRuleOptions") {
            let result = new UnusedAccountRuleOptions();
            result.init(data);
            return result;
        }
        if (data["name"] === "UserNameChangedRecentlyRuleOptions") {
            let result = new UserNameChangedRecentlyRuleOptions();
            result.init(data);
            return result;
        }
        let result = new ChaniaRuleOptions();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this._discriminator;
        data["friendlyName"] = this.friendlyName;
        data["description"] = this.description;
        data["enabled"] = this.enabled;
        if (Array.isArray(this.eligibleEvents)) {
            data["eligibleEvents"] = [];
            for (let item of this.eligibleEvents)
                data["eligibleEvents"].push(item);
        }
        return data;
    }
}

export interface IChaniaRuleOptions {
    friendlyName?: string | undefined;
    description?: string | undefined;
    enabled?: boolean | undefined;
    eligibleEvents?: string[] | undefined;
}

export class AvailableBalanceRuleOptions extends ChaniaRuleOptions implements IAvailableBalanceRuleOptions {
    availableBalanceThresholdPercentage?: number | undefined;

    constructor(data?: IAvailableBalanceRuleOptions) {
        super(data);
        this._discriminator = "AvailableBalanceRuleOptions";
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.availableBalanceThresholdPercentage = _data["availableBalanceThresholdPercentage"];
        }
    }

    static override fromJS(data: any): AvailableBalanceRuleOptions {
        data = typeof data === 'object' ? data : {};
        let result = new AvailableBalanceRuleOptions();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["availableBalanceThresholdPercentage"] = this.availableBalanceThresholdPercentage;
        super.toJSON(data);
        return data;
    }
}

export interface IAvailableBalanceRuleOptions extends IChaniaRuleOptions {
    availableBalanceThresholdPercentage?: number | undefined;
}

export class DbAggregateRuleExecutionResult implements IDbAggregateRuleExecutionResult {
    id?: string | undefined;
    eventId?: string | undefined;
    createdAt?: Date | undefined;
    amount?: number | undefined;
    ipAddress?: string | undefined;
    subjectId?: string | undefined;
    name?: string | undefined;
    type?: string | undefined;
    data?: any | undefined;
    numberOfRulesExecuted?: number | undefined;
    results?: DbRuleExecutionResult[] | undefined;
    riskScore?: number | undefined;
    riskLevel?: string | undefined;

    constructor(data?: IDbAggregateRuleExecutionResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.eventId = _data["eventId"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.amount = _data["amount"];
            this.ipAddress = _data["ipAddress"];
            this.subjectId = _data["subjectId"];
            this.name = _data["name"];
            this.type = _data["type"];
            this.data = _data["data"];
            this.numberOfRulesExecuted = _data["numberOfRulesExecuted"];
            if (Array.isArray(_data["results"])) {
                this.results = [] as any;
                for (let item of _data["results"])
                    this.results!.push(DbRuleExecutionResult.fromJS(item));
            }
            this.riskScore = _data["riskScore"];
            this.riskLevel = _data["riskLevel"];
        }
    }

    static fromJS(data: any): DbAggregateRuleExecutionResult {
        data = typeof data === 'object' ? data : {};
        let result = new DbAggregateRuleExecutionResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["eventId"] = this.eventId;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["amount"] = this.amount;
        data["ipAddress"] = this.ipAddress;
        data["subjectId"] = this.subjectId;
        data["name"] = this.name;
        data["type"] = this.type;
        data["data"] = this.data;
        data["numberOfRulesExecuted"] = this.numberOfRulesExecuted;
        if (Array.isArray(this.results)) {
            data["results"] = [];
            for (let item of this.results)
                data["results"].push(item ? item.toJSON() : undefined as any);
        }
        data["riskScore"] = this.riskScore;
        data["riskLevel"] = this.riskLevel;
        return data;
    }
}

export interface IDbAggregateRuleExecutionResult {
    id?: string | undefined;
    eventId?: string | undefined;
    createdAt?: Date | undefined;
    amount?: number | undefined;
    ipAddress?: string | undefined;
    subjectId?: string | undefined;
    name?: string | undefined;
    type?: string | undefined;
    data?: any | undefined;
    numberOfRulesExecuted?: number | undefined;
    results?: DbRuleExecutionResult[] | undefined;
    riskScore?: number | undefined;
    riskLevel?: string | undefined;
}

export class DbAggregateRuleExecutionResultResultSet implements IDbAggregateRuleExecutionResultResultSet {
    count?: number | undefined;
    items?: DbAggregateRuleExecutionResult[] | undefined;

    constructor(data?: IDbAggregateRuleExecutionResultResultSet) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.count = _data["count"];
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(DbAggregateRuleExecutionResult.fromJS(item));
            }
        }
    }

    static fromJS(data: any): DbAggregateRuleExecutionResultResultSet {
        data = typeof data === 'object' ? data : {};
        let result = new DbAggregateRuleExecutionResultResultSet();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["count"] = this.count;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IDbAggregateRuleExecutionResultResultSet {
    count?: number | undefined;
    items?: DbAggregateRuleExecutionResult[] | undefined;
}

export class DbRuleExecutionResult implements IDbRuleExecutionResult {
    riskLevel?: RiskLevel | undefined;
    riskScore?: number | undefined;
    reason?: string | undefined;
    ruleName?: string | undefined;

    constructor(data?: IDbRuleExecutionResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.riskLevel = _data["riskLevel"];
            this.riskScore = _data["riskScore"];
            this.reason = _data["reason"];
            this.ruleName = _data["ruleName"];
        }
    }

    static fromJS(data: any): DbRuleExecutionResult {
        data = typeof data === 'object' ? data : {};
        let result = new DbRuleExecutionResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["riskLevel"] = this.riskLevel;
        data["riskScore"] = this.riskScore;
        data["reason"] = this.reason;
        data["ruleName"] = this.ruleName;
        return data;
    }
}

export interface IDbRuleExecutionResult {
    riskLevel?: RiskLevel | undefined;
    riskScore?: number | undefined;
    reason?: string | undefined;
    ruleName?: string | undefined;
}

export class HistoricalTransactionsOverMinimumAmountRuleOptions extends ChaniaRuleOptions implements IHistoricalTransactionsOverMinimumAmountRuleOptions {
    minimumAmount?: number | undefined;
    daysAgo?: number | undefined;

    constructor(data?: IHistoricalTransactionsOverMinimumAmountRuleOptions) {
        super(data);
        this._discriminator = "HistoricalTransactionsOverMinimumAmountRuleOptions";
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.minimumAmount = _data["minimumAmount"];
            this.daysAgo = _data["daysAgo"];
        }
    }

    static override fromJS(data: any): HistoricalTransactionsOverMinimumAmountRuleOptions {
        data = typeof data === 'object' ? data : {};
        let result = new HistoricalTransactionsOverMinimumAmountRuleOptions();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["minimumAmount"] = this.minimumAmount;
        data["daysAgo"] = this.daysAgo;
        super.toJSON(data);
        return data;
    }
}

export interface IHistoricalTransactionsOverMinimumAmountRuleOptions extends IChaniaRuleOptions {
    minimumAmount?: number | undefined;
    daysAgo?: number | undefined;
}

export class HttpValidationProblemDetails implements IHttpValidationProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
    errors?: { [key: string]: string[]; } | undefined;

    [key: string]: any;

    constructor(data?: IHttpValidationProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
            if (_data["errors"]) {
                this.errors = {} as any;
                for (let key in _data["errors"]) {
                    if (_data["errors"].hasOwnProperty(key))
                        (this.errors as any)![key] = _data["errors"][key] !== undefined ? _data["errors"][key] : [];
                }
            }
        }
    }

    static fromJS(data: any): HttpValidationProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new HttpValidationProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        if (this.errors) {
            data["errors"] = {};
            for (let key in this.errors) {
                if (this.errors.hasOwnProperty(key))
                    (data["errors"] as any)[key] = (this.errors as any)[key];
            }
        }
        return data;
    }
}

export interface IHttpValidationProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
    errors?: { [key: string]: string[]; } | undefined;

    [key: string]: any;
}

export class MuleAccountRuleOptions extends ChaniaRuleOptions implements IMuleAccountRuleOptions {

    constructor(data?: IMuleAccountRuleOptions) {
        super(data);
        this._discriminator = "MuleAccountRuleOptions";
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): MuleAccountRuleOptions {
        data = typeof data === 'object' ? data : {};
        let result = new MuleAccountRuleOptions();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IMuleAccountRuleOptions extends IChaniaRuleOptions {
}

export class PasswordChangedRecentlyRuleOptions extends ChaniaRuleOptions implements IPasswordChangedRecentlyRuleOptions {
    daysAgo?: number | undefined;

    constructor(data?: IPasswordChangedRecentlyRuleOptions) {
        super(data);
        this._discriminator = "PasswordChangedRecentlyRuleOptions";
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.daysAgo = _data["daysAgo"];
        }
    }

    static override fromJS(data: any): PasswordChangedRecentlyRuleOptions {
        data = typeof data === 'object' ? data : {};
        let result = new PasswordChangedRecentlyRuleOptions();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["daysAgo"] = this.daysAgo;
        super.toJSON(data);
        return data;
    }
}

export interface IPasswordChangedRecentlyRuleOptions extends IChaniaRuleOptions {
    daysAgo?: number | undefined;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export class RiskEvent implements IRiskEvent {
    readonly id?: string | undefined;
    amount?: number | undefined;
    ipAddress?: string | undefined;
    subjectId?: string | undefined;
    createdAt?: Date | undefined;
    name?: string | undefined;
    type?: string | undefined;
    data?: any | undefined;
    sourceId?: string | undefined;
    sourceTransId?: string | undefined;
    location?: string | undefined;
    sessionId?: string | undefined;
    countryIsoCode?: string | undefined;
    coordinates?: string | undefined;

    constructor(data?: IRiskEvent) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            (this as any).id = _data["id"];
            this.amount = _data["amount"];
            this.ipAddress = _data["ipAddress"];
            this.subjectId = _data["subjectId"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.name = _data["name"];
            this.type = _data["type"];
            this.data = _data["data"];
            this.sourceId = _data["sourceId"];
            this.sourceTransId = _data["sourceTransId"];
            this.location = _data["location"];
            this.sessionId = _data["sessionId"];
            this.countryIsoCode = _data["countryIsoCode"];
            this.coordinates = _data["coordinates"];
        }
    }

    static fromJS(data: any): RiskEvent {
        data = typeof data === 'object' ? data : {};
        let result = new RiskEvent();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["amount"] = this.amount;
        data["ipAddress"] = this.ipAddress;
        data["subjectId"] = this.subjectId;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["name"] = this.name;
        data["type"] = this.type;
        data["data"] = this.data;
        data["sourceId"] = this.sourceId;
        data["sourceTransId"] = this.sourceTransId;
        data["location"] = this.location;
        data["sessionId"] = this.sessionId;
        data["countryIsoCode"] = this.countryIsoCode;
        data["coordinates"] = this.coordinates;
        return data;
    }
}

export interface IRiskEvent {
    id?: string | undefined;
    amount?: number | undefined;
    ipAddress?: string | undefined;
    subjectId?: string | undefined;
    createdAt?: Date | undefined;
    name?: string | undefined;
    type?: string | undefined;
    data?: any | undefined;
    sourceId?: string | undefined;
    sourceTransId?: string | undefined;
    location?: string | undefined;
    sessionId?: string | undefined;
    countryIsoCode?: string | undefined;
    coordinates?: string | undefined;
}

export class RiskEventResultSet implements IRiskEventResultSet {
    count?: number | undefined;
    items?: RiskEvent[] | undefined;

    constructor(data?: IRiskEventResultSet) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.count = _data["count"];
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(RiskEvent.fromJS(item));
            }
        }
    }

    static fromJS(data: any): RiskEventResultSet {
        data = typeof data === 'object' ? data : {};
        let result = new RiskEventResultSet();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["count"] = this.count;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IRiskEventResultSet {
    count?: number | undefined;
    items?: RiskEvent[] | undefined;
}

export enum RiskLevel {
    None = "None",
    Low = "Low",
    Medium = "Medium",
    High = "High",
}

export class RiskModel implements IRiskModel {
    amount?: number | undefined;
    ipAddress?: string | undefined;
    subjectId?: string | undefined;
    name?: string | undefined;
    type?: string | undefined;
    data?: any | undefined;
    sourceId?: string | undefined;
    sourceTransId?: string | undefined;
    resultId?: string | undefined;
    sessionId?: string | undefined;

    constructor(data?: IRiskModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.amount = _data["amount"];
            this.ipAddress = _data["ipAddress"];
            this.subjectId = _data["subjectId"];
            this.name = _data["name"];
            this.type = _data["type"];
            this.data = _data["data"];
            this.sourceId = _data["sourceId"];
            this.sourceTransId = _data["sourceTransId"];
            this.resultId = _data["resultId"];
            this.sessionId = _data["sessionId"];
        }
    }

    static fromJS(data: any): RiskModel {
        data = typeof data === 'object' ? data : {};
        let result = new RiskModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["amount"] = this.amount;
        data["ipAddress"] = this.ipAddress;
        data["subjectId"] = this.subjectId;
        data["name"] = this.name;
        data["type"] = this.type;
        data["data"] = this.data;
        data["sourceId"] = this.sourceId;
        data["sourceTransId"] = this.sourceTransId;
        data["resultId"] = this.resultId;
        data["sessionId"] = this.sessionId;
        return data;
    }
}

export interface IRiskModel {
    amount?: number | undefined;
    ipAddress?: string | undefined;
    subjectId?: string | undefined;
    name?: string | undefined;
    type?: string | undefined;
    data?: any | undefined;
    sourceId?: string | undefined;
    sourceTransId?: string | undefined;
    resultId?: string | undefined;
    sessionId?: string | undefined;
}

export class RiskRuleDto implements IRiskRuleDto {
    name?: string | undefined;
    friendlyName?: string | undefined;
    description?: string | undefined;
    enabled?: boolean | undefined;

    constructor(data?: IRiskRuleDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.friendlyName = _data["friendlyName"];
            this.description = _data["description"];
            this.enabled = _data["enabled"];
        }
    }

    static fromJS(data: any): RiskRuleDto {
        data = typeof data === 'object' ? data : {};
        let result = new RiskRuleDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["friendlyName"] = this.friendlyName;
        data["description"] = this.description;
        data["enabled"] = this.enabled;
        return data;
    }
}

export interface IRiskRuleDto {
    name?: string | undefined;
    friendlyName?: string | undefined;
    description?: string | undefined;
    enabled?: boolean | undefined;
}

export class RiskRuleDtoResultSet implements IRiskRuleDtoResultSet {
    count?: number | undefined;
    items?: RiskRuleDto[] | undefined;

    constructor(data?: IRiskRuleDtoResultSet) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.count = _data["count"];
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(RiskRuleDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): RiskRuleDtoResultSet {
        data = typeof data === 'object' ? data : {};
        let result = new RiskRuleDtoResultSet();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["count"] = this.count;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IRiskRuleDtoResultSet {
    count?: number | undefined;
    items?: RiskRuleDto[] | undefined;
}

export class RuleExecutionResult implements IRuleExecutionResult {
    riskLevel?: RiskLevel | undefined;
    readonly riskScore?: number | undefined;
    readonly reason?: string | undefined;
    readonly ruleName?: string | undefined;

    constructor(data?: IRuleExecutionResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.riskLevel = _data["riskLevel"];
            (this as any).riskScore = _data["riskScore"];
            (this as any).reason = _data["reason"];
            (this as any).ruleName = _data["ruleName"];
        }
    }

    static fromJS(data: any): RuleExecutionResult {
        data = typeof data === 'object' ? data : {};
        let result = new RuleExecutionResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["riskLevel"] = this.riskLevel;
        data["riskScore"] = this.riskScore;
        data["reason"] = this.reason;
        data["ruleName"] = this.ruleName;
        return data;
    }
}

export interface IRuleExecutionResult {
    riskLevel?: RiskLevel | undefined;
    riskScore?: number | undefined;
    reason?: string | undefined;
    ruleName?: string | undefined;
}

export class TransactionOverMinimumAmountRuleOptions extends ChaniaRuleOptions implements ITransactionOverMinimumAmountRuleOptions {
    minimumAmount?: number | undefined;

    constructor(data?: ITransactionOverMinimumAmountRuleOptions) {
        super(data);
        this._discriminator = "TransactionOverMinimumAmountRuleOptions";
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.minimumAmount = _data["minimumAmount"];
        }
    }

    static override fromJS(data: any): TransactionOverMinimumAmountRuleOptions {
        data = typeof data === 'object' ? data : {};
        let result = new TransactionOverMinimumAmountRuleOptions();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["minimumAmount"] = this.minimumAmount;
        super.toJSON(data);
        return data;
    }
}

export interface ITransactionOverMinimumAmountRuleOptions extends IChaniaRuleOptions {
    minimumAmount?: number | undefined;
}

export class UnusedAccountRuleOptions extends ChaniaRuleOptions implements IUnusedAccountRuleOptions {
    daysAgoFrom?: number | undefined;
    daysAgoTo?: number | undefined;

    constructor(data?: IUnusedAccountRuleOptions) {
        super(data);
        this._discriminator = "UnusedAccountRuleOptions";
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.daysAgoFrom = _data["daysAgoFrom"];
            this.daysAgoTo = _data["daysAgoTo"];
        }
    }

    static override fromJS(data: any): UnusedAccountRuleOptions {
        data = typeof data === 'object' ? data : {};
        let result = new UnusedAccountRuleOptions();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["daysAgoFrom"] = this.daysAgoFrom;
        data["daysAgoTo"] = this.daysAgoTo;
        super.toJSON(data);
        return data;
    }
}

export interface IUnusedAccountRuleOptions extends IChaniaRuleOptions {
    daysAgoFrom?: number | undefined;
    daysAgoTo?: number | undefined;
}

export class UserNameChangedRecentlyRuleOptions extends ChaniaRuleOptions implements IUserNameChangedRecentlyRuleOptions {
    daysAgo?: number | undefined;

    constructor(data?: IUserNameChangedRecentlyRuleOptions) {
        super(data);
        this._discriminator = "UserNameChangedRecentlyRuleOptions";
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.daysAgo = _data["daysAgo"];
        }
    }

    static override fromJS(data: any): UserNameChangedRecentlyRuleOptions {
        data = typeof data === 'object' ? data : {};
        let result = new UserNameChangedRecentlyRuleOptions();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["daysAgo"] = this.daysAgo;
        super.toJSON(data);
        return data;
    }
}

export interface IUserNameChangedRecentlyRuleOptions extends IChaniaRuleOptions {
    daysAgo?: number | undefined;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}