using System;
using System.Collections.Generic;
using System.Security.Claims;
using Indice.AspNetCore.Identity.Data.Models;

namespace Indice.AspNetCore.Identity.TrustedDeviceAuthorization.Models
{
    /// <summary>
    /// Models an authorization code for a trusted device.
    /// </summary>
    internal class TrustedDeviceAuthorizationCode
    {
        /// <summary>
        /// The <see cref="DateTime"/> that the code was created.
        /// </summary>
        public DateTime CreationTime { get; set; }
        /// <summary>
        /// The lifetime of the code expressed in seconds.
        /// </summary>
        public int Lifetime { get; set; }
        /// <summary>
        /// The client id.
        /// </summary>
        public string ClientId { get; set; }
        /// <summary>
        /// The device id.
        /// </summary>
        public string DeviceId { get; set; }
        /// <summary>
        /// The way a device interacts with the identity system for trusted authorization.
        /// </summary>
        public InteractionMode InteractionMode { get; set; }
        /// <summary>
        /// The principal associated with this code.
        /// </summary>
        public ClaimsPrincipal Subject { get; set; }
        /// <summary>
        /// The scopes that were requested.
        /// </summary>
        public IEnumerable<string> RequestedScopes { get; set; }
        /// <summary>
        /// Code challenge generated by the consumer.
        /// </summary>
        public string CodeChallenge { get; set; }
    }
}
