name: "Publish to NuGet"

permissions:
  contents: read

on:
  workflow_dispatch:
  # push:
  #    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:
    permissions:
      contents: read
      actions: read
      checks: write
    runs-on: windows-2025
    steps:
    # Checkout
    - name: Harden Runner
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
      with:
        egress-policy: audit

    - name: Checkout Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    
    #Setup .NET Core
    - name: Setup .NET
      uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
      with:
        global-json-file: ./global.json
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
        
    # Setup Node.js
    - name: Use Node.js 24.x
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: 24

    # Necessary for gulp tasks
    - name: NPM Install and Build Identity UI
      run: |
        cd src/Indice.Features.Identity.UI
        npm install --force
        npm run gulp -- copy:libs
        npm run gulp -- sass
  
    #Create .nuget dir
    - name: Create .nuget dir
      shell: pwsh
      run: |
        if (!(Test-Path -Path ".\.nuget" ))
        {
          New-Item -ItemType "directory" -Path ".\.nuget"
        }
        if (!(Test-Path -Path ".\.nuget\packages" ))
        {
          New-Item -ItemType "directory" -Path ".\.nuget\packages"
        }
    
    # BUILD
    - name: Dotnet restore
      run: dotnet restore

    - name: Dotnet build SPAs
      run: dotnet build Indice.Platform.Ecmascript.slnf --no-restore --configuration Release

    - name: Dotnet build
      run: dotnet build Indice.Platform.slnf --no-restore --configuration Release
     
    # TEST 
    - name: Test with dotnet
      run: dotnet test --no-build --configuration Release --logger trx --results-directory "TestResults"
    
    # TEST REPORT
    - name: Test Reporter
      uses: dorny/test-reporter@b082adf0eced0765477756c2a610396589b8c637 # v2.5.0
      if: always()
      with:
        name: DotNET Tests
        path: "TestResults/*.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
        
    # Pack
    - name: Generate NuGet package
      run: ./pack.ps1

    # Push to NuGet
    - name: Push nuget packages
      run: dotnet nuget push '**/Indice*.nupkg' --skip-duplicate -k ${{ secrets.NUGET_AUTH_TOKEN }}
