name: PR Automated Testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-dotnet-tests:
    name: .NET Tests
    runs-on: windows-latest
    outputs:
      cache-key: ${{ steps.set-cache-key.outputs.cache_key }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Cache Key
        id: set-cache-key
        run: echo "cache_key=dotnet-build-${{ github.sha }}" >> $GITHUB_ENV

      - name: Dotnet build + test
        id: dotnet-build-test
        uses: ./.github/workflows/composites/build-test
        with:
          cacheKey: ${{ env.cache_key }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
      
      - name: Upload Cache Key as an Output
        run: echo "cache_key=${{ env.cache_key }}" >> $GITHUB_ENV

      # - name: Code analysis
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     ref: ${{ github.event.pull_request.head.ref }}
      #     workflow: CodeQL Advanced
      #     token: ${{ secrets.GITHUB_TOKEN }}
