name: PR Automated Testing

on:
  pull_request

jobs:
  run-dotnet-tests:
    name: .NET Tests
    runs-on: windows-latest
    steps:
      - name: Dotnet build + test
        id: dotnet-build-test
        uses: ./.github/workflows/composites/build-test
    
    