<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Indice.Features.Messages.AspNetCore\Indice.Features.Messages.AspNetCore.csproj" />
  </ItemGroup>
</Project>
